// Database grammatica Genki I
// Ogni voce: {lesson, point, type, prompt, options, correct, explanation}
// type: 'particle' | 'translate_jp_it' | 'translate_it_jp' | 'transform' | 'choose_question_word' | 'fill_answer' | 'spot_error'

const GRAMMAR_L1 = [
  {lesson:1, point:"Xは Yです", type:"particle",
   prompt:"せんこう ___ にほんごです。",
   options:["は", "の", "か", "を"],
   correct:"は",
   explanation:"「は」segna l'argomento della frase: 'per quanto riguarda la specializzazione, è il giapponese'."},
  {lesson:1, point:"Xは Yです", type:"translate_jp_it",
   prompt:"だいがくのせんせいです。",
   options:["Sono un professore universitario", "Sono uno studente universitario", "È la mia università", "Sono un insegnante di liceo"],
   correct:"Sono un professore universitario",
   explanation:"だいがく (università) + の + せんせい (insegnante) = 'insegnante universitario/professore'."},
  {lesson:1, point:"Xは Yです", type:"translate_it_jp",
   prompt:"Come si dice 'Sono Maria' (nome: メアリー)?",
   options:["メアリーです。", "メアリーはです。", "メアリーでした。", "メアリーですか。"],
   correct:"メアリーです。",
   explanation:"Basta nome + です per dire 'sono ...'; non serve un soggetto esplicito come 'io'."},
  {lesson:1, point:"Frasi interrogative", type:"transform",
   prompt:"Come diventa una domanda: 「りゅうがくせいです。」?",
   options:["りゅうがくせいですか。", "りゅうがくせいはです。", "りゅうがくせいでした。", "りゅうがくせいますか。"],
   correct:"りゅうがくせいですか。",
   explanation:"Basta aggiungere か alla fine della frase per trasformarla in domanda — nessun punto interrogativo necessario."},
  {lesson:1, point:"Frasi interrogative", type:"choose_question_word",
   prompt:"Come chiedi 'Quanti anni hai?'",
   options:["なんさいですか。", "なんじですか。", "なんばんですか。", "なんねんせいですか。"],
   correct:"なんさいですか。",
   explanation:"なんさい chiede l'età; なんじ chiede l'ora; なんばん chiede il numero; なんねんせい chiede l'anno di corso."},
  {lesson:1, point:"Frasi interrogative", type:"translate_jp_it",
   prompt:"でんわばんごうは なんばんですか。",
   options:["Qual è il tuo numero di telefono?", "Quanti anni hai?", "Che ore sono?", "In che anno sei?"],
   correct:"Qual è il tuo numero di telefono?",
   explanation:"でんわばんごう = numero di telefono; なんばん = che numero."},
  {lesson:1, point:"Frasi interrogative", type:"fill_answer",
   prompt:"A: せんこうは なんですか。 B: ___",
   options:["にほんごです。", "がくせいです。", "はいです。", "そうですか。"],
   correct:"にほんごです。",
   explanation:"La domanda chiede 'qual è la tua specializzazione?' — la risposta deve nominare una materia."},
  {lesson:1, point:"Noun1のNoun2", type:"translate_it_jp",
   prompt:"Come si dice 'uno studente di giapponese'?",
   options:["にほんごのがくせい", "がくせいのにほんご", "にほんごはがくせい", "がくせいはにほんご"],
   correct:"にほんごのがくせい",
   explanation:"Il secondo nome (がくせい) è l'idea principale; il primo (にほんご) la specifica. の va tra i due nella direzione 'specifica'+の+'principale'."},
  {lesson:1, point:"Noun1のNoun2", type:"particle",
   prompt:"たけしさん ___ でんわばんごう",
   options:["の", "は", "か", "を"],
   correct:"の",
   explanation:"の collega due nomi come un possessivo: 'il numero di telefono di Takeshi'."},
  {lesson:1, point:"Noun1のNoun2", type:"translate_jp_it",
   prompt:"にほんのだいがく",
   options:["un'università in Giappone", "il Giappone dell'università", "un'università giapponese (nel senso di persona)", "il mio paese è un'università"],
   correct:"un'università in Giappone",
   explanation:"にほん (Giappone) + の + だいがく (università) = 'un'università in/del Giappone'."},
  {lesson:1, point:"Noun1のNoun2", type:"spot_error",
   prompt:"Quale frase è sbagliata?",
   options:["だいがくのせんせいです。", "せんこうはにほんごです。", "にほんごはせんこうのです。", "いま なんじですか。"],
   correct:"にほんごはせんこうのです。",
   explanation:"の va sempre tra due nomi (Noun1のNoun2), non può stare da solo dopo です — la forma corretta sarebbe せんこうはにほんごです。"}
];

const GRAMMAR_L2 = [
  {lesson:2, point:"これ／それ／あれ／どれ", type:"translate_jp_it",
   prompt:"あれは わたしの ペンです。",
   options:["Quella (là) è la mia penna", "Questa è la mia penna", "Quella (vicino a te) è la mia penna", "Di chi è questa penna?"],
   correct:"Quella (là) è la mia penna",
   explanation:"あれ indica qualcosa lontano sia da chi parla sia da chi ascolta."},
  {lesson:2, point:"これ／それ／あれ／どれ", type:"fill_answer",
   prompt:"___ は さんぜんえんです。 (indicando un oggetto lontano da entrambi)",
   options:["これ", "それ", "あれ", "どれ"],
   correct:"あれ",
   explanation:"あれ si usa per un oggetto lontano sia dal parlante sia dall'ascoltatore."},
  {lesson:2, point:"この／その／あの／どの + Noun", type:"translate_jp_it",
   prompt:"あのがくせいは りゅうがくせいです。",
   options:["Quello studente (là) è uno studente straniero", "Questo studente è giapponese", "Quale studente è straniero?", "Quello studente non è straniero"],
   correct:"Quello studente (là) è uno studente straniero",
   explanation:"あの + nome indica qualcosa/qualcuno lontano da entrambi gli interlocutori, proprio come あれ."},
  {lesson:2, point:"この／その／あの／どの + Noun", type:"spot_error",
   prompt:"Quale frase è sbagliata?",
   options:["これとけいは いくらですか。", "このとけいは いくらですか。", "そのとけいは さんぜんえんです。", "あのがくせいは りゅうがくせいです。"],
   correct:"これとけいは いくらですか。",
   explanation:"これ/それ/あれ NON possono precedere direttamente un nome — serve la forma con の: この/その/あの + nome."},
  {lesson:2, point:"ここ／そこ／あそこ／どこ", type:"translate_it_jp",
   prompt:"Come chiedi 'Dov'è l'ufficio postale?'",
   options:["ゆうびんきょくは どこですか。", "ゆうびんきょくは だれですか。", "ゆうびんきょくは なんですか。", "どこは ゆうびんきょくですか。"],
   correct:"ゆうびんきょくは どこですか。",
   explanation:"どこ è la parola interrogativa per 'dove' e va nella posizione dell'informazione richiesta, dopo は."},
  {lesson:2, point:"だれの Noun", type:"translate_jp_it",
   prompt:"これは だれの かばんですか。",
   options:["Di chi è questa borsa?", "Dov'è questa borsa?", "Questa è la mia borsa", "Quanto costa questa borsa?"],
   correct:"Di chi è questa borsa?",
   explanation:"だれの + nome chiede a chi appartiene qualcosa: だれ (chi) + の (particella possessiva)."},
  {lesson:2, point:"Noun も", type:"particle",
   prompt:"たけしさんはにほんじんです。ゆいさん___にほんじんです。",
   options:["は", "の", "も", "を"],
   correct:"も",
   explanation:"も significa 'anche' e sostituisce は quando aggiungi un elemento con la stessa proprietà già menzionata."},
  {lesson:2, point:"Noun も", type:"translate_jp_it",
   prompt:"ゆいさんも にほんじんです。",
   options:["Anche Yui è giapponese", "Yui non è giapponese", "Yui è giapponese?", "Chi è giapponese come Yui?"],
   correct:"Anche Yui è giapponese",
   explanation:"も dopo ゆいさん indica che anche lei condivide la proprietà 'essere giapponese' già detta per qualcun altro."},
  {lesson:2, point:"Noun じゃないです", type:"transform",
   prompt:"Trasforma in negativo: 「がくせいです。」",
   options:["がくせいじゃないです。", "がくせいですか。", "がくせいでした。", "がくせいはです。"],
   correct:"がくせいじゃないです。",
   explanation:"Per negare X は Y です, si sostituisce です con じゃないです (versione colloquiale)."},
  {lesson:2, point:"Noun じゃないです", type:"fill_answer",
   prompt:"A: にほんじんですか。 B: いいえ、___。",
   options:["にほんじんじゃないです。", "じゃないです。", "にほんじんです。", "いいえです。"],
   correct:"にほんじんじゃないです。",
   explanation:"です e じゃない non possono stare da soli: devono sempre essere accompagnati da un nome, anche nelle risposte brevi."},
  {lesson:2, point:"〜ね／〜よ", type:"choose_question_word",
   prompt:"Quale finale usi se vuoi conferma dall'ascoltatore ('giusto?')?",
   options:["ね", "よ", "か", "も"],
   correct:"ね",
   explanation:"ね cerca conferma o accordo da chi ascolta ('vero?', 'giusto?'); よ invece afferma con sicurezza qualcosa che l'altro potrebbe non sapere."},
  {lesson:2, point:"〜ね／〜よ", type:"translate_jp_it",
   prompt:"とんかつは さかなじゃないですよ。",
   options:["Ti assicuro che il tonkatsu non è pesce", "Il tonkatsu è pesce, vero?", "È il tonkatsu pesce?", "Il tonkatsu non è pesce, vero?"],
   correct:"Ti assicuro che il tonkatsu non è pesce",
   explanation:"よ comunica sicurezza/informazione nuova a chi ascolta, non richiede conferma come ね."}
];

const GRAMMAR_L3 = [
  {lesson:3, point:"Particella を (oggetto diretto)", type:"particle",
   prompt:"コーヒー ___ のみます。",
   options:["を", "で", "に", "へ"],
   correct:"を",
   explanation:"を segna l'oggetto diretto del verbo: 'bevo IL CAFFÈ'."},
  {lesson:3, point:"Particella で (luogo dell'azione)", type:"particle",
   prompt:"としょかん ___ ほんをよみます。",
   options:["を", "で", "に", "へ"],
   correct:"で",
   explanation:"で indica il luogo in cui avviene l'azione: 'leggo libri IN biblioteca'."},
  {lesson:3, point:"Particella に (meta del movimento)", type:"particle",
   prompt:"がっこう ___ いきます。",
   options:["を", "で", "に", "も"],
   correct:"に",
   explanation:"に (o へ) indica la meta del movimento con verbi come 行く: 'vado A scuola'."},
  {lesson:3, point:"Riferimenti temporali (に)", type:"spot_error",
   prompt:"Quale frase è sbagliata?",
   options:["あしたに きます。", "にちようびに いきます。", "くがつに かえります。", "まいばん テレビを みます。"],
   correct:"あしたに きます。",
   explanation:"Espressioni relative al presente come あした (domani) NON prendono la particella に — si dice semplicemente あしたきます。"},
  {lesson:3, point:"Riferimenti temporali (に)", type:"translate_it_jp",
   prompt:"Come dici 'Vado a Kyoto domenica'?",
   options:["にちようびに きょうとにいきます。", "にちようび きょうとにいきます。", "きょうとに にちようびいきます。", "にちようびは きょうとです。"],
   correct:"にちようびに きょうとにいきます。",
   explanation:"I giorni della settimana e le ore precise richiedono に; きょうと (meta) prende anch'essa に."},
  {lesson:3, point:"〜ませんか (invito)", type:"translate_jp_it",
   prompt:"テニスを しませんか。",
   options:["Ti va di giocare a tennis (con me)?", "Giochi a tennis?", "Non giochi a tennis", "Perché non giochi a tennis da solo?"],
   correct:"Ti va di giocare a tennis (con me)?",
   explanation:"ませんか (forma negativa + か) si usa per fare un invito, non per fare una semplice domanda — a differenza di ますか."},
  {lesson:3, point:"〜ませんか (invito)", type:"translate_it_jp",
   prompt:"Come inviti qualcuno a pranzare con te?",
   options:["昼ご飯を 食べませんか。", "昼ご飯を 食べますか。", "昼ご飯を 食べます。", "昼ご飯は 何ですか。"],
   correct:"昼ご飯を 食べませんか。",
   explanation:"ませんか trasforma la domanda in un invito gentile: 'non mangeresti con me?' = 'ti va di mangiare?'"},
  {lesson:3, point:"Avverbi di frequenza", type:"fill_answer",
   prompt:"たけしさんは ___ べんきょうしません。 (Takeshi non studia molto)",
   options:["よく", "ときどき", "あまり", "まいにち"],
   correct:"あまり",
   explanation:"あまり + forma negativa = 'non molto'; ぜんぜん + negativo = 'per niente'. よく e ときどき si usano con l'affermativo."},
  {lesson:3, point:"Avverbi di frequenza", type:"translate_jp_it",
   prompt:"私は よく 図書館に 行きます。",
   options:["Vado spesso in biblioteca", "Non vado mai in biblioteca", "Vado a volte in biblioteca", "Sono appena andato in biblioteca"],
   correct:"Vado spesso in biblioteca",
   explanation:"よく prima del verbo affermativo significa 'spesso'."},
  {lesson:3, point:"Ordine delle parole", type:"choose_question_word",
   prompt:"Qual è l'ordine tipico di una frase giapponese?",
   options:["topic → tempo → luogo → oggetto → verbo", "verbo → oggetto → luogo → tempo → topic", "oggetto → verbo → topic → tempo → luogo", "topic → verbo → oggetto → tempo → luogo"],
   correct:"topic → tempo → luogo → oggetto → verbo",
   explanation:"Il verbo va sempre alla fine; gli altri elementi (con le loro particelle) sono relativamente flessibili ma seguono spesso quest'ordine."},
  {lesson:3, point:"La particella は (argomenti non-soggetto)", type:"translate_jp_it",
   prompt:"ばんごはんは？",
   options:["Che mi dici della cena?", "Hai cenato?", "Cos'è la cena?", "La cena è pronta"],
   correct:"Che mi dici della cena?",
   explanation:"は può introdurre come argomento anche una frase incompleta, invitando l'ascoltatore a completare il pensiero — qui ばんごはん non è nemmeno il soggetto, ma l'oggetto sottinteso."}
];

const GRAMMAR_L4 = [
  {lesson:4, point:"Xがあります／います", type:"fill_answer",
   prompt:"あそこに 留学生___ います。",
   options:["が", "は", "を", "に"],
   correct:"が",
   explanation:"Con あります/います la cosa/persona che esiste è segnata da が, non da は."},
  {lesson:4, point:"Xがあります／います", type:"choose_question_word",
   prompt:"Quale verbo usi per dire che C'È un cane (いぬ)?",
   options:["います", "あります", "です", "います and あります sono intercambiabili"],
   correct:"います",
   explanation:"います si usa per persone/animali (esseri viventi che si muovono); あります per cose inanimate."},
  {lesson:4, point:"Xがあります／います", type:"translate_jp_it",
   prompt:"テレビが ありません。",
   options:["Non ho la TV", "Non guardo la TV", "La TV non funziona", "Dov'è la TV?"],
   correct:"Non ho la TV",
   explanation:"あります può indicare anche il possesso: 'テレビがあります' = 'ho la TV', in negativo = 'non ce l'ho'."},
  {lesson:4, point:"Descrivere dove si trovano le cose", type:"translate_it_jp",
   prompt:"Come dici 'La banca è vicino alla biblioteca'?",
   options:["ぎんこうは としょかんの ちかくです。", "としょかんは ぎんこうの ちかくです。", "ぎんこうが としょかん ちかくです。", "ちかくは ぎんこうと としょかんです。"],
   correct:"ぎんこうは としょかんの ちかくです。",
   explanation:"Struttura: XはYの(luogo)です — 'X è nel/vicino al luogo di Y'."},
  {lesson:4, point:"Descrivere dove si trovano le cose", type:"translate_jp_it",
   prompt:"レストランは スーパーと 病院の 間です。",
   options:["Il ristorante è tra il supermercato e l'ospedale", "Il ristorante è vicino al supermercato", "Il supermercato è dietro il ristorante", "L'ospedale è di fronte al ristorante"],
   correct:"Il ristorante è tra il supermercato e l'ospedale",
   explanation:"'XとYのあいだ' significa 'tra X e Y'."},
  {lesson:4, point:"も (con altre particelle)", type:"fill_answer",
   prompt:"私は きょう 大阪に 行きます。京都___ 行きます。 (vado anche a Kyoto)",
   options:["にも", "もに", "はも", "でも"],
   correct:"にも",
   explanation:"も sostituisce は/が/を da solo, ma con に e で si aggiunge dopo: にも, でも."},
  {lesson:4, point:"も (con altre particelle)", type:"spot_error",
   prompt:"Quale frase è sbagliata?",
   options:["カフェもで 本を読みます。", "カフェでも 本を読みます。", "日曜日にも 学校に来ます。", "かばんも 買います。"],
   correct:"カフェもで 本を読みます。",
   explanation:"L'ordine corretto è particella+も (でも, にも), non も+particella."},
  {lesson:4, point:"一時間 (durata)", type:"translate_jp_it",
   prompt:"三時間ぐらい 勉強します。",
   options:["Studio per circa tre ore", "Studio alle tre", "Studio tre volte", "Studio dalle tre"],
   correct:"Studio per circa tre ore",
   explanation:"三時間 (tre ore) è un sostantivo 'nudo' che esprime durata, senza particella; ぐらい aggiunge 'circa'."},
  {lesson:4, point:"一時間 (durata)", type:"translate_it_jp",
   prompt:"Come dici 'per un'ora e mezza circa'?",
   options:["一時間半ぐらい", "一時間ぐらい半", "半一時間ぐらい", "一時間ぐらいと半"],
   correct:"一時間半ぐらい",
   explanation:"半 (e mezza) va subito dopo l'unità di tempo; ぐらい (circa) va sempre per ultimo."},
  {lesson:4, point:"たくさん (quantità)", type:"spot_error",
   prompt:"Quale frase NON è corretta per dire 'Ho scattato molte foto'?",
   options:["写真をたくさん撮ります。", "たくさん写真を撮ります。", "写真たくさんを撮ります。", "(entrambe le prime due sono corrette)"],
   correct:"写真たくさんを撮ります。",
   explanation:"たくさん va prima del nome (たくさん写真を) oppure dopo la particella を (写真をたくさん) — mai tra nome e particella."},
  {lesson:4, point:"と (collegare nomi / 'insieme a')", type:"translate_it_jp",
   prompt:"Come dici 'Parlo giapponese e inglese'?",
   options:["日本語と英語を話します。", "日本語も英語を話します。", "日本語や英語を話します。", "日本語の英語を話します。"],
   correct:"日本語と英語を話します。",
   explanation:"と collega due nomi nel senso di 'e' (lista completa, a differenza di や che implica 'eccetera')."},
  {lesson:4, point:"と ('insieme a')", type:"translate_jp_it",
   prompt:"メアリーさんは ソラさんと 韓国に 行きます。",
   options:["Mary andrà in Corea con Sora", "Mary e Sora sono coreane", "Mary va in Corea invece di Sora", "Sora accompagna Mary in aeroporto"],
   correct:"Mary andrà in Corea con Sora",
   explanation:"と dopo una persona significa 'insieme a/con quella persona'."}
];

const GRAMMAR_L5 = [
  {lesson:5, point:"Avverbi di grado (とても／すごく／ちょっと)", type:"translate_jp_it",
   prompt:"沖縄の海は とても きれいです。",
   options:["Il mare di Okinawa è molto bello", "Il mare di Okinawa è un po' bello", "Il mare di Okinawa non è per niente bello", "Il mare di Okinawa era bello"],
   correct:"Il mare di Okinawa è molto bello",
   explanation:"とても (molto) si mette prima dell'aggettivo per intensificarlo."},
  {lesson:5, point:"Aggettivi che modificano un nome", type:"translate_it_jp",
   prompt:"Come dici 'un film interessante'?",
   options:["おもしろい映画", "映画おもしろい", "おもしろいな映画", "映画のおもしろい"],
   correct:"おもしろい映画",
   explanation:"Gli い-aggettivi precedono direttamente il nome, nella forma dizionario, senza particelle."},
  {lesson:5, point:"Aggettivi che modificano un nome", type:"translate_it_jp",
   prompt:"Come dici 'una foto bella' (kirei)?",
   options:["きれいな写真", "きれい写真", "写真きれいな", "きれいの写真"],
   correct:"きれいな写真",
   explanation:"Gli な-aggettivi richiedono な prima del nome che modificano — な torna, anche se non compare prima di です."},
  {lesson:5, point:"Aggettivi che modificano un nome", type:"spot_error",
   prompt:"Quale frase è sbagliata?",
   options:["山下先生はこわい先生です。", "ここはとてもにぎやか町です。", "京都できれいな写真を撮ります。", "おもしろい映画を見ます。"],
   correct:"ここはとてもにぎやか町です。",
   explanation:"にぎやか è un な-aggettivo: prima di un nome serve にぎやかな町, non にぎやか町."},
  {lesson:5, point:"好き（な）／きらい（な）", type:"translate_it_jp",
   prompt:"Come dici 'Robert ama le sue lezioni di giapponese'?",
   options:["ロバートさんは日本語のクラスが好きです。", "ロバートさんは日本語のクラスを好きです。", "ロバートさんが日本語のクラス好きです。", "日本語のクラスはロバートさんが好きです。"],
   correct:"ロバートさんは日本語のクラスが好きです。",
   explanation:"Struttura: X は Y が 好き/きらい です — l'oggetto amato/odiato (Y) prende が, non を."},
  {lesson:5, point:"好き（な）／きらい（な）", type:"translate_jp_it",
   prompt:"たけしさんはコーヒーが大好きです。",
   options:["Takeshi adora il caffè", "Takeshi odia il caffè", "Takeshi beve caffè", "A Takeshi non piace il caffè"],
   correct:"Takeshi adora il caffè",
   explanation:"大好き (intensificato con 大) significa 'piacere moltissimo/amare', più forte del semplice 好き."},
  {lesson:5, point:"好き（な）／きらい（な）", type:"translate_it_jp",
   prompt:"Come dici 'questo è il mio libro preferito'?",
   options:["これは私の好きな本です。", "これは私が好きな本です。", "これは私の好き本です。", "これは私の本が好きです。"],
   correct:"これは私の好きな本です。",
   explanation:"好きな può modificare un nome proprio come un な-aggettivo: 'il libro che mi piace' = 'il mio libro preferito'."},
  {lesson:5, point:"〜ましょう／〜ましょうか", type:"translate_jp_it",
   prompt:"一緒に図書館で勉強しましょう。",
   options:["Studiamo insieme in biblioteca!", "Studierò in biblioteca", "Studi in biblioteca?", "Non studiare in biblioteca"],
   correct:"Studiamo insieme in biblioteca!",
   explanation:"〜ましょう corrisponde a 'facciamo...', un invito/proposta d'azione condivisa."},
  {lesson:5, point:"〜ましょう／〜ましょうか", type:"translate_jp_it",
   prompt:"あそこでコーヒーを飲みましょうか。",
   options:["Beviamo un caffè laggiù?", "Bevo il caffè laggiù", "Hai bevuto il caffè laggiù?", "Non bere il caffè laggiù"],
   correct:"Beviamo un caffè laggiù?",
   explanation:"〜ましょうか aggiunge una sfumatura interrogativa alla proposta: 'che ne dici di...?'"},
  {lesson:5, point:"Contare gli oggetti", type:"translate_jp_it",
   prompt:"リーさんは Tシャツを 三枚 買います。",
   options:["Lee compra tre magliette", "Lee compra la maglietta numero tre", "Lee ha tre magliette", "Lee compra tre cose"],
   correct:"Lee compra tre magliette",
   explanation:"三枚 (numero + contatore 枚 per oggetti piatti) segue il nome+particella, non lo precede."},
  {lesson:5, point:"Contare gli oggetti", type:"choose_question_word",
   prompt:"Dove va di solito la parola numerale (es. 三枚) in una frase giapponese?",
   options:["Dopo il nome e la sua particella", "Prima del nome", "All'inizio della frase", "Subito dopo il verbo"],
   correct:"Dopo il nome e la sua particella",
   explanation:"A differenza dell'inglese/italiano, in giapponese il numero segue tipicamente l'oggetto contato: 'Tシャツを三枚' (magliette-tre), non 'tre magliette'."}
];

const GRAMMAR_L6 = [
  {lesson:6, point:"〜から (perché / la ragione)", type:"translate_jp_it",
   prompt:"バスに乗りましょう。タクシーは高いですから。",
   options:["Prendiamo l'autobus, perché i taxi sono cari", "I taxi sono cari come l'autobus", "L'autobus è caro quanto il taxi", "Perché prendiamo il taxi invece dell'autobus?"],
   correct:"Prendiamo l'autobus, perché i taxi sono cari",
   explanation:"から alla fine di una frase spiega il motivo di quanto detto prima (o dopo, se l'ordine è invertito)."},
  {lesson:6, point:"〜から (perché / la ragione)", type:"fill_answer",
   prompt:"私は今晩勉強します。あしたテストがあります___。",
   options:["から", "ので", "が", "けど"],
   correct:"から",
   explanation:"から si aggiunge alla fine della frase che spiega la causa/motivazione."},
  {lesson:6, point:"〜ましょうか (offrire aiuto)", type:"translate_jp_it",
   prompt:"荷物を持ちましょうか。",
   options:["Ti porto io la borsa?", "Porti tu la borsa?", "Ho portato la borsa", "Non portare la borsa"],
   correct:"Ti porto io la borsa?",
   explanation:"ましょうか può significare anche 'lascia che faccia io...', offrendo aiuto — diverso da 'facciamo insieme' visto in Lezione 5."},
  {lesson:6, point:"〜ましょうか (offrire aiuto)", type:"translate_it_jp",
   prompt:"Come offri il tuo aiuto per aprire qualcosa (dicendo 'lo faccio io')?",
   options:["（私が）やりましょうか。", "（私が）やりますか。", "やってください。", "やりましょう。"],
   correct:"（私が）やりましょうか。",
   explanation:"ましょうか con soggetto 私が (implicito o esplicito) offre di fare qualcosa per l'altra persona."}
];

const GRAMMAR_L7 = [
  {lesson:7, point:"Xは Yが (descrivere attributi fisici)", type:"translate_it_jp",
   prompt:"Come dici 'Tom ha i capelli lunghi' (alla giapponese, con doppio soggetto)?",
   options:["トムさんは髪が長いです。", "トムさんの髪は長いです。", "トムさんを髪が長いです。", "髪はトムさんが長いです。"],
   correct:"トムさんは髪が長いです。",
   explanation:"Per descrivere un attributo fisico si preferisce X は Y が (persona は parte del corpo が) invece di X の Y は."},
  {lesson:7, point:"Xは Yが (descrivere attributi fisici)", type:"translate_jp_it",
   prompt:"山下先生は頭がいいです。",
   options:["Il professor Yamashita è intelligente", "Il professor Yamashita ha mal di testa", "La testa del professor Yamashita è grande", "Il professor Yamashita capisce la sua testa"],
   correct:"Il professor Yamashita è intelligente",
   explanation:"頭がいい è un'espressione idiomatica con la struttura Xは Yが: letteralmente 'per quanto riguarda X, la testa è buona' = intelligente."},
  {lesson:7, point:"Contare le persone", type:"fill_answer",
   prompt:"Come si dice 'una persona' (contatore per persone)?",
   options:["ひとり", "いちにん", "ひとにん", "いちり"],
   correct:"ひとり",
   explanation:"'Una persona' e 'due persone' sono irregolari: ひとり e ふたり, non seguono il pattern numero+にん."},
  {lesson:7, point:"Contare le persone", type:"fill_answer",
   prompt:"Come si dice 'quattro persone'?",
   options:["よにん", "よんにん", "しにん", "よんじん"],
   correct:"よにん",
   explanation:"Il contatore にん per 4 usa よ (non よん come per gli altri contesti): よにん."}
];

const GRAMMAR_L8 = [
  {lesson:8, point:"Verbo（辞書形）+ の が 好き／上手", type:"translate_jp_it",
   prompt:"ロバートさんは料理を作るのが上手です。",
   options:["Robert è bravo a cucinare", "Robert odia cucinare", "Robert cucina ora", "Robert ha cucinato ieri"],
   correct:"Robert è bravo a cucinare",
   explanation:"Verbo (forma dizionario) + の trasforma l'azione in un nome; poi が上手です dice 'è bravo a farla'."},
  {lesson:8, point:"Verbo（辞書形）+ の が 好き／上手", type:"translate_it_jp",
   prompt:"Come dici 'Mi piace studiare il giapponese' usando questa struttura?",
   options:["日本語を勉強するのが好きです。", "日本語を勉強するが好きです。", "日本語の勉強好きです。", "日本語を勉強しての好きです。"],
   correct:"日本語を勉強するのが好きです。",
   explanation:"Serve la forma dizionario del verbo (勉強する) seguita da の per nominalizzarla, poi が好きです."},
  {lesson:8, point:"La particella soggetto が", type:"translate_jp_it",
   prompt:"ロバートさんが沖縄に行きました。",
   options:["È stato ROBERT ad andare a Okinawa (informazione nuova)", "Robert è andato a Okinawa (fatto già noto)", "Robert va spesso a Okinawa", "Chi è andato a Okinawa?"],
   correct:"È stato ROBERT ad andare a Okinawa (informazione nuova)",
   explanation:"が invece di は enfatizza il soggetto come informazione nuova: risponde a una domanda implicita 'chi è andato?'"},
  {lesson:8, point:"La particella soggetto が", type:"fill_answer",
   prompt:"だれ___ 沖縄に行きましたか。 (Chi è andato a Okinawa?)",
   options:["が", "は", "を", "の"],
   correct:"が",
   explanation:"Le parole interrogative come だれ e なに, quando sono soggetto, sono sempre seguite da が, mai da は."},
  {lesson:8, point:"何か／何も", type:"fill_answer",
   prompt:"猫は ___ 食べましたか。 (Il gatto ha mangiato qualcosa?)",
   options:["何か", "何も", "何が", "何を"],
   correct:"何か",
   explanation:"何か significa 'qualcosa' nelle domande e affermazioni positive."},
  {lesson:8, point:"何か／何も", type:"translate_jp_it",
   prompt:"猫は何も食べませんでした。",
   options:["Il gatto non ha mangiato niente", "Il gatto ha mangiato qualcosa", "Il gatto ha mangiato tutto", "Il gatto non mangia mai"],
   correct:"Il gatto non ha mangiato niente",
   explanation:"何も + forma negativa = 'niente/nulla' — combinazione obbligatoria in giapponese."}
];

const GRAMMAR_L9 = [
  {lesson:9, point:"Modificare un nome con aggettivi/frasi (frasi relative)", type:"translate_jp_it",
   prompt:"猫が好きな人",
   options:["una persona a cui piacciono i gatti", "un gatto a cui piace una persona", "una persona che ha un gatto", "un gatto simpatico"],
   correct:"una persona a cui piacciono i gatti",
   explanation:"In giapponese la frase modificante (猫が好きな) precede direttamente il nome (人) — non serve un pronome relativo come 'che/who'."},
  {lesson:9, point:"Modificare un nome con aggettivi/frasi (frasi relative)", type:"translate_it_jp",
   prompt:"Come dici 'una persona interessante' usando questa struttura di base?",
   options:["おもしろい人", "人はおもしろい", "おもしろいの人", "人がおもしろいの"],
   correct:"おもしろい人",
   explanation:"Un semplice aggettivo alla forma dizionario/base precede il nome esattamente come un aggettivo qualsiasi — lo stesso principio si estende a frasi più complesse."},
  {lesson:9, point:"Modificare un nome con aggettivi/frasi (frasi relative)", type:"translate_jp_it",
   prompt:"髪が長い人",
   options:["una persona con i capelli lunghi", "una persona senza capelli", "i capelli di una persona sono lunghi", "una persona alta"],
   correct:"una persona con i capelli lunghi",
   explanation:"La struttura Xが長い (visto in Lezione 7 per gli attributi fisici) può modificare direttamente un nome: 'una persona [tale che] i capelli sono lunghi'."},
  {lesson:9, point:"から: spiegazione prima della situazione", type:"translate_jp_it",
   prompt:"忙しいですから、テレビを見ません。",
   options:["Sono impegnato, quindi non guardo la TV", "Non sono impegnato, guardo la TV", "Guardo la TV perché sono impegnato", "Sono impegnato quando guardo la TV"],
   correct:"Sono impegnato, quindi non guardo la TV",
   explanation:"Mettendo 'spiegazione+から' all'inizio, la frase si legge come 'perciò/quindi', più vicina all'ordine naturale italiano."},
  {lesson:9, point:"から: spiegazione prima della situazione", type:"choose_question_word",
   prompt:"Quale ordine mette la SPIEGAZIONE prima della SITUAZIONE?",
   options:["spiegazione + から、situazione。", "situazione。spiegazione + から。", "situazione + から、spiegazione。", "Sono equivalenti solo se si usa と"],
   correct:"spiegazione + から、situazione。",
   explanation:"Questo ordine corrisponde a 'perciò/quindi' in italiano, mentre l'ordine opposto (situazione prima) corrisponde a 'perché'."}
];

const GRAMMAR_L10 = [
  {lesson:10, point:"Comparazione tra due elementi", type:"translate_jp_it",
   prompt:"中国のほうが日本より大きいです。",
   options:["La Cina è più grande del Giappone", "Il Giappone è più grande della Cina", "La Cina è grande quanto il Giappone", "Il Giappone è il più grande"],
   correct:"La Cina è più grande del Giappone",
   explanation:"Struttura: AのほうがBより(proprietà) = 'A è più (proprietà) di B'. のほうが segna l'elemento superiore, より quello di paragone."},
  {lesson:10, point:"Comparazione tra due elementi", type:"translate_it_jp",
   prompt:"Come chiedi 'Cosa è più freddo, il Giappone o il Canada?'",
   options:["日本とカナダとどちらのほうが寒いですか。", "日本はカナダより寒いですか。", "どちらが日本とカナダですか。", "日本とカナダが寒いです。"],
   correct:"日本とカナダとどちらのほうが寒いですか。",
   explanation:"Per confrontare due elementi in una domanda: AとBとどちらのほうが(proprietà)ですか。"},
  {lesson:10, point:"Comparazione tra tre o più elementi", type:"translate_jp_it",
   prompt:"秋がいちばん好きです。",
   options:["L'autunno mi piace più di tutti", "Non mi piace affatto l'autunno", "L'autunno è la prima stagione", "Preferisco l'autunno all'estate"],
   correct:"L'autunno mi piace più di tutti",
   explanation:"いちばん (il più) si usa per confronti tra tre o più elementi, mentre のほう si usa solo tra due."},
  {lesson:10, point:"Comparazione tra tre o più elementi", type:"spot_error",
   prompt:"Quale frase è sbagliata? (confronto tra tre nazioni)",
   options:["カナダとフランスと日本の中で、どこのほうが寒いですか。", "カナダとフランスと日本の中で、どこがいちばん寒いですか。", "カナダがいちばん寒いと思います。", "季節の中でいつがいちばん好きですか。"],
   correct:"カナダとフランスと日本の中で、どこのほうが寒いですか。",
   explanation:"のほう si usa solo per confronti tra DUE elementi; con tre o più si usa いちばん, non のほう."},
  {lesson:10, point:"Aggettivo／Nome + の (pronome indefinito)", type:"translate_jp_it",
   prompt:"私は黒いセーターを持っています。赤いのも持っています。",
   options:["Ho un maglione nero. Ne ho anche uno rosso.", "Ho un maglione nero e rosso.", "Il mio maglione nero è diventato rosso.", "Non ho maglioni rossi."],
   correct:"Ho un maglione nero. Ne ho anche uno rosso.",
   explanation:"の sostituisce un nome già menzionato (セーター) per evitare di ripeterlo: '赤いの' = 'quello rosso'."},
  {lesson:10, point:"Aggettivo／Nome + の (pronome indefinito)", type:"translate_it_jp",
   prompt:"Come dici 'Non è il mio; è di Mary' (parlando di una borsa già menzionata)?",
   options:["私のじゃないです。メアリーさんのです。", "私はじゃないです。メアリーさんはです。", "私のかばんじゃないです。メアリーさんのかばんです。(entrambe corrette, ma...)", "私のはじゃないです。メアリーさんのはです。"],
   correct:"私のじゃないです。メアリーさんのです。",
   explanation:"の dopo un nome/pronome può significare anche 'il/la ... di qualcuno', evitando di ripetere l'oggetto (かばん)."},
  {lesson:10, point:"どこかに／どこにも (estensione di 何か／何も)", type:"fill_answer",
   prompt:"A: どこ___ 行きましたか。 B: いいえ、どこ___も 行きませんでした。",
   options:["へ／へ", "が／が", "を／を", "の／の"],
   correct:"へ／へ",
   explanation:"どこか/どこも richiedono comunque le particelle non-base come へ, に, で — solo は/が/を vengono omesse."},
  {lesson:10, point:"どこかに／どこにも (estensione di 何か／何も)", type:"translate_jp_it",
   prompt:"だれかに会いましたか。",
   options:["Hai visto qualcuno?", "Hai visto tutti?", "Chi hai visto?", "Non hai visto nessuno?"],
   correct:"Hai visto qualcuno?",
   explanation:"だれか = 'qualcuno' (positivo/domanda); だれも + negativo = 'nessuno'."},
  {lesson:10, point:"で (mezzo/strumento)", type:"particle",
   prompt:"バス ___ 駅まで行きました。",
   options:["で", "に", "を", "が"],
   correct:"で",
   explanation:"で indica il mezzo di trasporto o lo strumento usato per fare qualcosa: 'in autobus'."},
  {lesson:10, point:"で (mezzo/strumento)", type:"translate_jp_it",
   prompt:"はしでご飯を食べます。",
   options:["Mangio il riso con le bacchette", "Mangio riso e bacchette", "Le bacchette sono per il riso", "Compro le bacchette per il riso"],
   correct:"Mangio il riso con le bacchette",
   explanation:"で dopo uno strumento (はし = bacchette) significa 'con, usando quello strumento'."}
];

// Pool combinato di tutte le domande di grammatica (tutte le lezioni 1-10, esclusa la coniugazione di verbi/aggettivi)
const GRAMMAR_ALL = [...GRAMMAR_L1, ...GRAMMAR_L2, ...GRAMMAR_L3, ...GRAMMAR_L4, ...GRAMMAR_L5, ...GRAMMAR_L6, ...GRAMMAR_L7, ...GRAMMAR_L8, ...GRAMMAR_L9, ...GRAMMAR_L10];
