// Database grammatica Genki I
// Ogni voce: {lesson, point, type, prompt, options, correct, explanation}
// type: 'particle' | 'translate_jp_it' | 'translate_it_jp' | 'transform' | 'choose_question_word' | 'fill_answer' | 'spot_error'

const GRAMMAR_L1 = [
  {lesson:1, point:"Xは Yです", type:"particle",
   prompt:"せんこう ___ にほんごです。",
   options:["は", "の", "か", "を"],
   correct:"は",
   explanation:"「は」segna l'argomento della frase: 'per quanto riguarda la specializzazione, è il giapponese'."},
  {lesson:1, point:"Xは Yです", type:"translate_jp_it",
   prompt:"だいがくのせんせいです。",
   options:["Sono un professore universitario", "Sono uno studente universitario", "È la mia università", "Sono un insegnante di liceo"],
   correct:"Sono un professore universitario",
   explanation:"だいがく (università) + の + せんせい (insegnante) = 'insegnante universitario/professore'."},
  {lesson:1, point:"Xは Yです", type:"translate_it_jp",
   prompt:"Come si dice 'Sono Maria' (nome: メアリー)?",
   options:["メアリーです。", "メアリーはです。", "メアリーでした。", "メアリーですか。"],
   correct:"メアリーです。",
   explanation:"Basta nome + です per dire 'sono ...'; non serve un soggetto esplicito come 'io'."},
  {lesson:1, point:"Frasi interrogative", type:"transform",
   prompt:"Come diventa una domanda: 「りゅうがくせいです。」?",
   options:["りゅうがくせいですか。", "りゅうがくせいはです。", "りゅうがくせいでした。", "りゅうがくせいますか。"],
   correct:"りゅうがくせいですか。",
   explanation:"Basta aggiungere か alla fine della frase per trasformarla in domanda — nessun punto interrogativo necessario."},
  {lesson:1, point:"Frasi interrogative", type:"choose_question_word",
   prompt:"Come chiedi 'Quanti anni hai?'",
   options:["なんさいですか。", "なんじですか。", "なんばんですか。", "なんねんせいですか。"],
   correct:"なんさいですか。",
   explanation:"なんさい chiede l'età; なんじ chiede l'ora; なんばん chiede il numero; なんねんせい chiede l'anno di corso."},
  {lesson:1, point:"Frasi interrogative", type:"translate_jp_it",
   prompt:"でんわばんごうは なんばんですか。",
   options:["Qual è il tuo numero di telefono?", "Quanti anni hai?", "Che ore sono?", "In che anno sei?"],
   correct:"Qual è il tuo numero di telefono?",
   explanation:"でんわばんごう = numero di telefono; なんばん = che numero."},
  {lesson:1, point:"Frasi interrogative", type:"fill_answer",
   prompt:"A: せんこうは なんですか。 B: ___",
   options:["にほんごです。", "がくせいです。", "はいです。", "そうですか。"],
   correct:"にほんごです。",
   explanation:"La domanda chiede 'qual è la tua specializzazione?' — la risposta deve nominare una materia."},
  {lesson:1, point:"Noun1のNoun2", type:"translate_it_jp",
   prompt:"Come si dice 'uno studente di giapponese'?",
   options:["にほんごのがくせい", "がくせいのにほんご", "にほんごはがくせい", "がくせいはにほんご"],
   correct:"にほんごのがくせい",
   explanation:"Il secondo nome (がくせい) è l'idea principale; il primo (にほんご) la specifica. の va tra i due nella direzione 'specifica'+の+'principale'."},
  {lesson:1, point:"Noun1のNoun2", type:"particle",
   prompt:"たけしさん ___ でんわばんごう",
   options:["の", "は", "か", "を"],
   correct:"の",
   explanation:"の collega due nomi come un possessivo: 'il numero di telefono di Takeshi'."},
  {lesson:1, point:"Noun1のNoun2", type:"translate_jp_it",
   prompt:"にほんのだいがく",
   options:["un'università in Giappone", "il Giappone dell'università", "un'università giapponese (nel senso di persona)", "il mio paese è un'università"],
   correct:"un'università in Giappone",
   explanation:"にほん (Giappone) + の + だいがく (università) = 'un'università in/del Giappone'."},
  {lesson:1, point:"Noun1のNoun2", type:"spot_error",
   prompt:"Quale frase è sbagliata?",
   options:["だいがくのせんせいです。", "せんこうはにほんごです。", "にほんごはせんこうのです。", "いま なんじですか。"],
   correct:"にほんごはせんこうのです。",
   explanation:"の va sempre tra due nomi (Noun1のNoun2), non può stare da solo dopo です — la forma corretta sarebbe せんこうはにほんごです。"}
];

const GRAMMAR_L2 = [
  {lesson:2, point:"これ／それ／あれ／どれ", type:"translate_jp_it",
   prompt:"あれは わたしの ペンです。",
   options:["Quella (là) è la mia penna", "Questa è la mia penna", "Quella (vicino a te) è la mia penna", "Di chi è questa penna?"],
   correct:"Quella (là) è la mia penna",
   explanation:"あれ indica qualcosa lontano sia da chi parla sia da chi ascolta."},
  {lesson:2, point:"これ／それ／あれ／どれ", type:"fill_answer",
   prompt:"___ は さんぜんえんです。 (indicando un oggetto lontano da entrambi)",
   options:["これ", "それ", "あれ", "どれ"],
   correct:"あれ",
   explanation:"あれ si usa per un oggetto lontano sia dal parlante sia dall'ascoltatore."},
  {lesson:2, point:"この／その／あの／どの + Noun", type:"translate_jp_it",
   prompt:"あのがくせいは りゅうがくせいです。",
   options:["Quello studente (là) è uno studente straniero", "Questo studente è giapponese", "Quale studente è straniero?", "Quello studente non è straniero"],
   correct:"Quello studente (là) è uno studente straniero",
   explanation:"あの + nome indica qualcosa/qualcuno lontano da entrambi gli interlocutori, proprio come あれ."},
  {lesson:2, point:"この／その／あの／どの + Noun", type:"spot_error",
   prompt:"Quale frase è sbagliata?",
   options:["これとけいは いくらですか。", "このとけいは いくらですか。", "そのとけいは さんぜんえんです。", "あのがくせいは りゅうがくせいです。"],
   correct:"これとけいは いくらですか。",
   explanation:"これ/それ/あれ NON possono precedere direttamente un nome — serve la forma con の: この/その/あの + nome."},
  {lesson:2, point:"ここ／そこ／あそこ／どこ", type:"translate_it_jp",
   prompt:"Come chiedi 'Dov'è l'ufficio postale?'",
   options:["ゆうびんきょくは どこですか。", "ゆうびんきょくは だれですか。", "ゆうびんきょくは なんですか。", "どこは ゆうびんきょくですか。"],
   correct:"ゆうびんきょくは どこですか。",
   explanation:"どこ è la parola interrogativa per 'dove' e va nella posizione dell'informazione richiesta, dopo は."},
  {lesson:2, point:"だれの Noun", type:"translate_jp_it",
   prompt:"これは だれの かばんですか。",
   options:["Di chi è questa borsa?", "Dov'è questa borsa?", "Questa è la mia borsa", "Quanto costa questa borsa?"],
   correct:"Di chi è questa borsa?",
   explanation:"だれの + nome chiede a chi appartiene qualcosa: だれ (chi) + の (particella possessiva)."},
  {lesson:2, point:"Noun も", type:"particle",
   prompt:"たけしさんはにほんじんです。ゆいさん___にほんじんです。",
   options:["は", "の", "も", "を"],
   correct:"も",
   explanation:"も significa 'anche' e sostituisce は quando aggiungi un elemento con la stessa proprietà già menzionata."},
  {lesson:2, point:"Noun も", type:"translate_jp_it",
   prompt:"ゆいさんも にほんじんです。",
   options:["Anche Yui è giapponese", "Yui non è giapponese", "Yui è giapponese?", "Chi è giapponese come Yui?"],
   correct:"Anche Yui è giapponese",
   explanation:"も dopo ゆいさん indica che anche lei condivide la proprietà 'essere giapponese' già detta per qualcun altro."},
  {lesson:2, point:"Noun じゃないです", type:"transform",
   prompt:"Trasforma in negativo: 「がくせいです。」",
   options:["がくせいじゃないです。", "がくせいですか。", "がくせいでした。", "がくせいはです。"],
   correct:"がくせいじゃないです。",
   explanation:"Per negare X は Y です, si sostituisce です con じゃないです (versione colloquiale)."},
  {lesson:2, point:"Noun じゃないです", type:"fill_answer",
   prompt:"A: にほんじんですか。 B: いいえ、___。",
   options:["にほんじんじゃないです。", "じゃないです。", "にほんじんです。", "いいえです。"],
   correct:"にほんじんじゃないです。",
   explanation:"です e じゃない non possono stare da soli: devono sempre essere accompagnati da un nome, anche nelle risposte brevi."},
  {lesson:2, point:"〜ね／〜よ", type:"choose_question_word",
   prompt:"Quale finale usi se vuoi conferma dall'ascoltatore ('giusto?')?",
   options:["ね", "よ", "か", "も"],
   correct:"ね",
   explanation:"ね cerca conferma o accordo da chi ascolta ('vero?', 'giusto?'); よ invece afferma con sicurezza qualcosa che l'altro potrebbe non sapere."},
  {lesson:2, point:"〜ね／〜よ", type:"translate_jp_it",
   prompt:"とんかつは さかなじゃないですよ。",
   options:["Ti assicuro che il tonkatsu non è pesce", "Il tonkatsu è pesce, vero?", "È il tonkatsu pesce?", "Il tonkatsu non è pesce, vero?"],
   correct:"Ti assicuro che il tonkatsu non è pesce",
   explanation:"よ comunica sicurezza/informazione nuova a chi ascolta, non richiede conferma come ね."}
];

const GRAMMAR_L3 = [
  {lesson:3, point:"Particella を (oggetto diretto)", type:"particle",
   prompt:"コーヒー ___ のみます。",
   options:["を", "で", "に", "へ"],
   correct:"を",
   explanation:"を segna l'oggetto diretto del verbo: 'bevo IL CAFFÈ'."},
  {lesson:3, point:"Particella で (luogo dell'azione)", type:"particle",
   prompt:"としょかん ___ ほんをよみます。",
   options:["を", "で", "に", "へ"],
   correct:"で",
   explanation:"で indica il luogo in cui avviene l'azione: 'leggo libri IN biblioteca'."},
  {lesson:3, point:"Particella に (meta del movimento)", type:"particle",
   prompt:"がっこう ___ いきます。",
   options:["を", "で", "に", "も"],
   correct:"に",
   explanation:"に (o へ) indica la meta del movimento con verbi come 行く（いく）: 'vado A scuola'."},
  {lesson:3, point:"Riferimenti temporali (に)", type:"spot_error",
   prompt:"Quale frase è sbagliata?",
   options:["あしたに きます。", "にちようびに いきます。", "くがつに かえります。", "まいばん テレビを みます。"],
   correct:"あしたに きます。",
   explanation:"Espressioni relative al presente come あした (domani) NON prendono la particella に — si dice semplicemente あしたきます。"},
  {lesson:3, point:"Riferimenti temporali (に)", type:"translate_it_jp",
   prompt:"Come dici 'Vado a Kyoto domenica'?",
   options:["にちようびに きょうとにいきます。", "にちようび きょうとにいきます。", "きょうとに にちようびいきます。", "にちようびは きょうとです。"],
   correct:"にちようびに きょうとにいきます。",
   explanation:"I giorni della settimana e le ore precise richiedono に; きょうと (meta) prende anch'essa に."},
  {lesson:3, point:"〜ませんか (invito)", type:"translate_jp_it",
   prompt:"テニスを しませんか。",
   options:["Ti va di giocare a tennis (con me)?", "Giochi a tennis?", "Non giochi a tennis", "Perché non giochi a tennis da solo?"],
   correct:"Ti va di giocare a tennis (con me)?",
   explanation:"ませんか (forma negativa + か) si usa per fare un invito, non per fare una semplice domanda — a differenza di ますか."},
  {lesson:3, point:"〜ませんか (invito)", type:"translate_it_jp",
   prompt:"Come inviti qualcuno a pranzare con te?",
   options:["昼ご飯（ひるごはん）を 食べません（たべません）か。", "昼ご飯（ひるごはん）を 食べますか（たべますか）。", "昼ご飯（ひるごはん）を 食べます（たべます）。", "昼ご飯（ひるごはん）は 何（なに）ですか。"],
   correct:"昼ご飯（ひるごはん）を 食べません（たべません）か。",
   explanation:"ませんか trasforma la domanda in un invito gentile: 'non mangeresti con me?' = 'ti va di mangiare?'"},
  {lesson:3, point:"Avverbi di frequenza", type:"fill_answer",
   prompt:"たけしさんは ___ べんきょうしません。 (Takeshi non studia molto)",
   options:["よく", "ときどき", "あまり", "まいにち"],
   correct:"あまり",
   explanation:"あまり + forma negativa = 'non molto'; ぜんぜん + negativo = 'per niente'. よく e ときどき si usano con l'affermativo."},
  {lesson:3, point:"Avverbi di frequenza", type:"translate_jp_it",
   prompt:"私（わたし）は よく 図書館（としょかん）に 行きます（いきます）。",
   options:["Vado spesso in biblioteca", "Non vado mai in biblioteca", "Vado a volte in biblioteca", "Sono appena andato in biblioteca"],
   correct:"Vado spesso in biblioteca",
   explanation:"よく prima del verbo affermativo significa 'spesso'."},
  {lesson:3, point:"Ordine delle parole", type:"choose_question_word",
   prompt:"Qual è l'ordine tipico di una frase giapponese?",
   options:["topic → tempo → luogo → oggetto → verbo", "verbo → oggetto → luogo → tempo → topic", "oggetto → verbo → topic → tempo → luogo", "topic → verbo → oggetto → tempo → luogo"],
   correct:"topic → tempo → luogo → oggetto → verbo",
   explanation:"Il verbo va sempre alla fine; gli altri elementi (con le loro particelle) sono relativamente flessibili ma seguono spesso quest'ordine."},
  {lesson:3, point:"La particella は (argomenti non-soggetto)", type:"translate_jp_it",
   prompt:"ばんごはんは？",
   options:["Che mi dici della cena?", "Hai cenato?", "Cos'è la cena?", "La cena è pronta"],
   correct:"Che mi dici della cena?",
   explanation:"は può introdurre come argomento anche una frase incompleta, invitando l'ascoltatore a completare il pensiero — qui ばんごはん non è nemmeno il soggetto, ma l'oggetto sottinteso."}
];

const GRAMMAR_L4 = [
  {lesson:4, point:"Xがあります／います", type:"fill_answer",
   prompt:"あそこに 留学生（りゅうがくせい）___ います。",
   options:["が", "は", "を", "に"],
   correct:"が",
   explanation:"Con あります/います la cosa/persona che esiste è segnata da が, non da は."},
  {lesson:4, point:"Xがあります／います", type:"choose_question_word",
   prompt:"Quale verbo usi per dire che C'È un cane (いぬ)?",
   options:["います", "あります", "です", "います and あります sono intercambiabili"],
   correct:"います",
   explanation:"います si usa per persone/animali (esseri viventi che si muovono); あります per cose inanimate."},
  {lesson:4, point:"Xがあります／います", type:"translate_jp_it",
   prompt:"テレビが ありません。",
   options:["Non ho la TV", "Non guardo la TV", "La TV non funziona", "Dov'è la TV?"],
   correct:"Non ho la TV",
   explanation:"あります può indicare anche il possesso: 'テレビがあります' = 'ho la TV', in negativo = 'non ce l'ho'."},
  {lesson:4, point:"Descrivere dove si trovano le cose", type:"translate_it_jp",
   prompt:"Come dici 'La banca è vicino alla biblioteca'?",
   options:["ぎんこうは としょかんの ちかくです。", "としょかんは ぎんこうの ちかくです。", "ぎんこうが としょかん ちかくです。", "ちかくは ぎんこうと としょかんです。"],
   correct:"ぎんこうは としょかんの ちかくです。",
   explanation:"Struttura: XはYの(luogo)です — 'X è nel/vicino al luogo di Y'."},
  {lesson:4, point:"Descrivere dove si trovano le cose", type:"translate_jp_it",
   prompt:"レストランは スーパーと 病院（びょういん）の 間です（あいだです）。",
   options:["Il ristorante è tra il supermercato e l'ospedale", "Il ristorante è vicino al supermercato", "Il supermercato è dietro il ristorante", "L'ospedale è di fronte al ristorante"],
   correct:"Il ristorante è tra il supermercato e l'ospedale",
   explanation:"'XとYのあいだ' significa 'tra X e Y'."},
  {lesson:4, point:"も (con altre particelle)", type:"fill_answer",
   prompt:"私（わたし）は きょう 大阪（おおさか）に 行きます（いきます）。京都（きょうと）___ 行きます（いきます）。 (vado anche a Kyoto)",
   options:["にも", "もに", "はも", "でも"],
   correct:"にも",
   explanation:"も sostituisce は/が/を da solo, ma con に e で si aggiunge dopo: にも, でも."},
  {lesson:4, point:"も (con altre particelle)", type:"spot_error",
   prompt:"Quale frase è sbagliata?",
   options:["カフェもで 本（ほん）を読みます（よみます）。", "カフェでも 本（ほん）を読みます（よみます）。", "日曜日（にちようび）にも 学校（がっこう）に来ます（きます）。", "かばんも 買います（かいます）。"],
   correct:"カフェもで 本（ほん）を読みます（よみます）。",
   explanation:"L'ordine corretto è particella+も (でも, にも), non も+particella."},
  {lesson:4, point:"一時間（いちじかん） (durata)", type:"translate_jp_it",
   prompt:"三時間（さんじかん）ぐらい 勉強します（べんきょうします）。",
   options:["Studio per circa tre ore", "Studio alle tre", "Studio tre volte", "Studio dalle tre"],
   correct:"Studio per circa tre ore",
   explanation:"三時間（さんじかん） (tre ore) è un sostantivo 'nudo' che esprime durata, senza particella; ぐらい aggiunge 'circa'."},
  {lesson:4, point:"一時間（いちじかん） (durata)", type:"translate_it_jp",
   prompt:"Come dici 'per un'ora e mezza circa'?",
   options:["一時間（いちじかん）半（はん）ぐらい", "一時間（いちじかん）ぐらい半（はん）", "半（はん）一時間（いちじかん）ぐらい", "一時間（いちじかん）ぐらいと半（はん）"],
   correct:"一時間（いちじかん）半（はん）ぐらい",
   explanation:"半（はん） (e mezza) va subito dopo l'unità di tempo; ぐらい (circa) va sempre per ultimo."},
  {lesson:4, point:"たくさん (quantità)", type:"spot_error",
   prompt:"Quale frase NON è corretta per dire 'Ho scattato molte foto'?",
   options:["写真（しゃしん）をたくさん撮ります（とります）。", "たくさん写真（しゃしん）を撮ります（とります）。", "写真（しゃしん）たくさんを撮ります（とります）。", "(entrambe le prime due sono corrette)"],
   correct:"写真（しゃしん）たくさんを撮ります（とります）。",
   explanation:"たくさん va prima del nome (たくさん写真（しゃしん）を) oppure dopo la particella を (写真（しゃしん）をたくさん) — mai tra nome e particella."},
  {lesson:4, point:"と (collegare nomi / 'insieme a')", type:"translate_it_jp",
   prompt:"Come dici 'Parlo giapponese e inglese'?",
   options:["日本語（にほんご）と英語（えいご）を話します（はなします）。", "日本語（にほんご）も英語（えいご）を話します（はなします）。", "日本語（にほんご）や英語（えいご）を話します（はなします）。", "日本語（にほんご）の英語（えいご）を話します（はなします）。"],
   correct:"日本語（にほんご）と英語（えいご）を話します（はなします）。",
   explanation:"と collega due nomi nel senso di 'e' (lista completa, a differenza di や che implica 'eccetera')."},
  {lesson:4, point:"と ('insieme a')", type:"translate_jp_it",
   prompt:"メアリーさんは ソラさんと 韓国（かんこく）に 行きます（いきます）。",
   options:["Mary andrà in Corea con Sora", "Mary e Sora sono coreane", "Mary va in Corea invece di Sora", "Sora accompagna Mary in aeroporto"],
   correct:"Mary andrà in Corea con Sora",
   explanation:"と dopo una persona significa 'insieme a/con quella persona'."}
];

const GRAMMAR_L5 = [
  {lesson:5, point:"Avverbi di grado (とても／すごく／ちょっと)", type:"translate_jp_it",
   prompt:"沖縄（おきなわ）の海（うみ）は とても きれいです。",
   options:["Il mare di Okinawa è molto bello", "Il mare di Okinawa è un po' bello", "Il mare di Okinawa non è per niente bello", "Il mare di Okinawa era bello"],
   correct:"Il mare di Okinawa è molto bello",
   explanation:"とても (molto) si mette prima dell'aggettivo per intensificarlo."},
  {lesson:5, point:"Aggettivi che modificano un nome", type:"translate_it_jp",
   prompt:"Come dici 'un film interessante'?",
   options:["おもしろい映画（えいが）", "映画（えいが）おもしろい", "おもしろいな映画（えいが）", "映画（えいが）のおもしろい"],
   correct:"おもしろい映画（えいが）",
   explanation:"Gli い-aggettivi precedono direttamente il nome, nella forma dizionario, senza particelle."},
  {lesson:5, point:"Aggettivi che modificano un nome", type:"translate_it_jp",
   prompt:"Come dici 'una foto bella' (kirei)?",
   options:["きれいな写真（しゃしん）", "きれい写真（しゃしん）", "写真（しゃしん）きれいな", "きれいの写真（しゃしん）"],
   correct:"きれいな写真（しゃしん）",
   explanation:"Gli な-aggettivi richiedono な prima del nome che modificano — な torna, anche se non compare prima di です."},
  {lesson:5, point:"Aggettivi che modificano un nome", type:"spot_error",
   prompt:"Quale frase è sbagliata?",
   options:["山下（やました）先生（せんせい）はこわい先生（せんせい）です。", "ここはとてもにぎやか町（まち）です。", "京都（きょうと）できれいな写真（しゃしん）を撮ります（とります）。", "おもしろい映画（えいが）を見ます（みます）。"],
   correct:"ここはとてもにぎやか町（まち）です。",
   explanation:"にぎやか è un な-aggettivo: prima di un nome serve にぎやかな町（まち）, non にぎやか町（まち）."},
  {lesson:5, point:"好き（すき）（な）／きらい（きらい）（な）", type:"translate_it_jp",
   prompt:"Come dici 'Robert ama le sue lezioni di giapponese'?",
   options:["ロバートさんは日本語（にほんご）のクラスが好きです（すきです）。", "ロバートさんは日本語（にほんご）のクラスを好きです（すきです）。", "ロバートさんが日本語（にほんご）のクラス好きです（すきです）。", "日本語（にほんご）のクラスはロバートさんが好きです（すきです）。"],
   correct:"ロバートさんは日本語（にほんご）のクラスが好きです（すきです）。",
   explanation:"Struttura: X は Y が 好き（すき）/きらい です — l'oggetto amato/odiato (Y) prende が, non を."},
  {lesson:5, point:"好き（すき）（な）／きらい（きらい）（な）", type:"translate_jp_it",
   prompt:"たけしさんはコーヒーが大好き（だいすき）です。",
   options:["Takeshi adora il caffè", "Takeshi odia il caffè", "Takeshi beve caffè", "A Takeshi non piace il caffè"],
   correct:"Takeshi adora il caffè",
   explanation:"大好き（だいすき） (intensificato con 大（だい）) significa 'piacere moltissimo/amare', più forte del semplice 好き（すき）."},
  {lesson:5, point:"好き（すき）（な）／きらい（きらい）（な）", type:"translate_it_jp",
   prompt:"Come dici 'questo è il mio libro preferito'?",
   options:["これは私（わたし）の好きな（すきな）本（ほん）です。", "これは私（わたし）が好きな（すきな）本（ほん）です。", "これは私（わたし）の好き（すき）本（ほん）です。", "これは私（わたし）の本（ほん）が好きです（すきです）。"],
   correct:"これは私（わたし）の好きな（すきな）本（ほん）です。",
   explanation:"好きな（すきな） può modificare un nome proprio come un な-aggettivo: 'il libro che mi piace' = 'il mio libro preferito'."},
  {lesson:5, point:"〜ましょう／〜ましょうか", type:"translate_jp_it",
   prompt:"一緒（いっしょ）に図書館（としょかん）で勉強しましょう（べんきょうしましょう）。",
   options:["Studiamo insieme in biblioteca!", "Studierò in biblioteca", "Studi in biblioteca?", "Non studiare in biblioteca"],
   correct:"Studiamo insieme in biblioteca!",
   explanation:"〜ましょう corrisponde a 'facciamo...', un invito/proposta d'azione condivisa."},
  {lesson:5, point:"〜ましょう／〜ましょうか", type:"translate_jp_it",
   prompt:"あそこでコーヒーを飲みましょうか（のみましょうか）。",
   options:["Beviamo un caffè laggiù?", "Bevo il caffè laggiù", "Hai bevuto il caffè laggiù?", "Non bere il caffè laggiù"],
   correct:"Beviamo un caffè laggiù?",
   explanation:"〜ましょうか aggiunge una sfumatura interrogativa alla proposta: 'che ne dici di...?'"},
  {lesson:5, point:"Contare gli oggetti", type:"translate_jp_it",
   prompt:"リーさんは Tシャツを 三枚（さんまい） 買います（かいます）。",
   options:["Lee compra tre magliette", "Lee compra la maglietta numero tre", "Lee ha tre magliette", "Lee compra tre cose"],
   correct:"Lee compra tre magliette",
   explanation:"三枚（さんまい） (numero + contatore 枚（まい） per oggetti piatti) segue il nome+particella, non lo precede."},
  {lesson:5, point:"Contare gli oggetti", type:"choose_question_word",
   prompt:"Dove va di solito la parola numerale (es. 三枚（さんまい）) in una frase giapponese?",
   options:["Dopo il nome e la sua particella", "Prima del nome", "All'inizio della frase", "Subito dopo il verbo"],
   correct:"Dopo il nome e la sua particella",
   explanation:"A differenza dell'inglese/italiano, in giapponese il numero segue tipicamente l'oggetto contato: 'Tシャツを三枚（さんまい）' (magliette-tre), non 'tre magliette'."}
];

const GRAMMAR_L6 = [
  {lesson:6, point:"〜から (perché / la ragione)", type:"translate_jp_it",
   prompt:"バスに乗りましょう（のりましょう）。タクシーは高いです（たかいです）から。",
   options:["Prendiamo l'autobus, perché i taxi sono cari", "I taxi sono cari come l'autobus", "L'autobus è caro quanto il taxi", "Perché prendiamo il taxi invece dell'autobus?"],
   correct:"Prendiamo l'autobus, perché i taxi sono cari",
   explanation:"から alla fine di una frase spiega il motivo di quanto detto prima (o dopo, se l'ordine è invertito)."},
  {lesson:6, point:"〜から (perché / la ragione)", type:"fill_answer",
   prompt:"私（わたし）は今晩（こんばん）勉強します（べんきょうします）。あしたテストがあります___。",
   options:["から", "ので", "が", "けど"],
   correct:"から",
   explanation:"から si aggiunge alla fine della frase che spiega la causa/motivazione."},
  {lesson:6, point:"〜ましょうか (offrire aiuto)", type:"translate_jp_it",
   prompt:"荷物（にもつ）を持ちましょうか（もちましょうか）。",
   options:["Ti porto io la borsa?", "Porti tu la borsa?", "Ho portato la borsa", "Non portare la borsa"],
   correct:"Ti porto io la borsa?",
   explanation:"ましょうか può significare anche 'lascia che faccia io...', offrendo aiuto — diverso da 'facciamo insieme' visto in Lezione 5."},
  {lesson:6, point:"〜ましょうか (offrire aiuto)", type:"translate_it_jp",
   prompt:"Come offri il tuo aiuto per aprire qualcosa (dicendo 'lo faccio io')?",
   options:["（私（わたし）が）やりましょうか。", "（私（わたし）が）やりますか。", "やってください。", "やりましょう。"],
   correct:"（私（わたし）が）やりましょうか。",
   explanation:"ましょうか con soggetto 私（わたし）が (implicito o esplicito) offre di fare qualcosa per l'altra persona."}
];

const GRAMMAR_L7 = [
  {lesson:7, point:"Xは Yが (descrivere attributi fisici)", type:"translate_it_jp",
   prompt:"Come dici 'Tom ha i capelli lunghi' (alla giapponese, con doppio soggetto)?",
   options:["トムさんは髪（かみ）が長いです（ながいです）。", "トムさんの髪（かみ）は長いです（ながいです）。", "トムさんを髪（かみ）が長いです（ながいです）。", "髪（かみ）はトムさんが長いです（ながいです）。"],
   correct:"トムさんは髪（かみ）が長いです（ながいです）。",
   explanation:"Per descrivere un attributo fisico si preferisce X は Y が (persona は parte del corpo が) invece di X の Y は."},
  {lesson:7, point:"Xは Yが (descrivere attributi fisici)", type:"translate_jp_it",
   prompt:"山下（やました）先生（せんせい）は頭（あたま）がいいです。",
   options:["Il professor Yamashita è intelligente", "Il professor Yamashita ha mal di testa", "La testa del professor Yamashita è grande", "Il professor Yamashita capisce la sua testa"],
   correct:"Il professor Yamashita è intelligente",
   explanation:"頭（あたま）がいい è un'espressione idiomatica con la struttura Xは Yが: letteralmente 'per quanto riguarda X, la testa è buona' = intelligente."},
  {lesson:7, point:"Contare le persone", type:"fill_answer",
   prompt:"Come si dice 'una persona' (contatore per persone)?",
   options:["ひとり", "いちにん", "ひとにん", "いちり"],
   correct:"ひとり",
   explanation:"'Una persona' e 'due persone' sono irregolari: ひとり e ふたり, non seguono il pattern numero+にん."},
  {lesson:7, point:"Contare le persone", type:"fill_answer",
   prompt:"Come si dice 'quattro persone'?",
   options:["よにん", "よんにん", "しにん", "よんじん"],
   correct:"よにん",
   explanation:"Il contatore にん per 4 usa よ (non よん come per gli altri contesti): よにん."}
];

const GRAMMAR_L8 = [
  {lesson:8, point:"Verbo（辞書形（じしょけい））+ の が 好き（すき）／上手（じょうず）", type:"translate_jp_it",
   prompt:"ロバートさんは料理（りょうり）を作る（つくる）のが上手（じょうず）です。",
   options:["Robert è bravo a cucinare", "Robert odia cucinare", "Robert cucina ora", "Robert ha cucinato ieri"],
   correct:"Robert è bravo a cucinare",
   explanation:"Verbo (forma dizionario) + の trasforma l'azione in un nome; poi が上手（じょうず）です dice 'è bravo a farla'."},
  {lesson:8, point:"Verbo（辞書形（じしょけい））+ の が 好き（すき）／上手（じょうず）", type:"translate_it_jp",
   prompt:"Come dici 'Mi piace studiare il giapponese' usando questa struttura?",
   options:["日本語（にほんご）を勉強する（べんきょうする）のが好きです（すきです）。", "日本語（にほんご）を勉強する（べんきょうする）が好きです（すきです）。", "日本語（にほんご）の勉強（べんきょう）好きです（すきです）。", "日本語（にほんご）を勉強して（べんきょうして）の好きです（すきです）。"],
   correct:"日本語（にほんご）を勉強する（べんきょうする）のが好きです（すきです）。",
   explanation:"Serve la forma dizionario del verbo (勉強する（べんきょうする）) seguita da の per nominalizzarla, poi が好きです（すきです）."},
  {lesson:8, point:"La particella soggetto が", type:"translate_jp_it",
   prompt:"ロバートさんが沖縄（おきなわ）に行きました（いきました）。",
   options:["È stato ROBERT ad andare a Okinawa (informazione nuova)", "Robert è andato a Okinawa (fatto già noto)", "Robert va spesso a Okinawa", "Chi è andato a Okinawa?"],
   correct:"È stato ROBERT ad andare a Okinawa (informazione nuova)",
   explanation:"が invece di は enfatizza il soggetto come informazione nuova: risponde a una domanda implicita 'chi è andato?'"},
  {lesson:8, point:"La particella soggetto が", type:"fill_answer",
   prompt:"だれ___ 沖縄（おきなわ）に行きましたか（いきましたか）。 (Chi è andato a Okinawa?)",
   options:["が", "は", "を", "の"],
   correct:"が",
   explanation:"Le parole interrogative come だれ e なに, quando sono soggetto, sono sempre seguite da が, mai da は."},
  {lesson:8, point:"何か（なにか）／何も（なにも）", type:"fill_answer",
   prompt:"猫（ねこ）は ___ 食べましたか（たべましたか）。 (Il gatto ha mangiato qualcosa?)",
   options:["何か（なにか）", "何も（なにも）", "何が（なにが）", "何を（なにを）"],
   correct:"何か（なにか）",
   explanation:"何か（なにか） significa 'qualcosa' nelle domande e affermazioni positive."},
  {lesson:8, point:"何か（なにか）／何も（なにも）", type:"translate_jp_it",
   prompt:"猫（ねこ）は何も（なにも）食べません（たべません）でした。",
   options:["Il gatto non ha mangiato niente", "Il gatto ha mangiato qualcosa", "Il gatto ha mangiato tutto", "Il gatto non mangia mai"],
   correct:"Il gatto non ha mangiato niente",
   explanation:"何も（なにも） + forma negativa = 'niente/nulla' — combinazione obbligatoria in giapponese."}
];

const GRAMMAR_L9 = [
  {lesson:9, point:"Modificare un nome con aggettivi/frasi (frasi relative)", type:"translate_jp_it",
   prompt:"猫（ねこ）が好きな（すきな）人（ひと）",
   options:["una persona a cui piacciono i gatti", "un gatto a cui piace una persona", "una persona che ha un gatto", "un gatto simpatico"],
   correct:"una persona a cui piacciono i gatti",
   explanation:"In giapponese la frase modificante (猫（ねこ）が好きな（すきな）) precede direttamente il nome (人（ひと）) — non serve un pronome relativo come 'che/who'."},
  {lesson:9, point:"Modificare un nome con aggettivi/frasi (frasi relative)", type:"translate_it_jp",
   prompt:"Come dici 'una persona interessante' usando questa struttura di base?",
   options:["おもしろい人（ひと）", "人（ひと）はおもしろい", "おもしろいの人（ひと）", "人（ひと）がおもしろいの"],
   correct:"おもしろい人（ひと）",
   explanation:"Un semplice aggettivo alla forma dizionario/base precede il nome esattamente come un aggettivo qualsiasi — lo stesso principio si estende a frasi più complesse."},
  {lesson:9, point:"Modificare un nome con aggettivi/frasi (frasi relative)", type:"translate_jp_it",
   prompt:"髪（かみ）が長い（ながい）人（ひと）",
   options:["una persona con i capelli lunghi", "una persona senza capelli", "i capelli di una persona sono lunghi", "una persona alta"],
   correct:"una persona con i capelli lunghi",
   explanation:"La struttura Xが長い（ながい） (visto in Lezione 7 per gli attributi fisici) può modificare direttamente un nome: 'una persona [tale che] i capelli sono lunghi'."},
  {lesson:9, point:"から: spiegazione prima della situazione", type:"translate_jp_it",
   prompt:"忙しい（いそがしい）ですから、テレビを見ません（みません）。",
   options:["Sono impegnato, quindi non guardo la TV", "Non sono impegnato, guardo la TV", "Guardo la TV perché sono impegnato", "Sono impegnato quando guardo la TV"],
   correct:"Sono impegnato, quindi non guardo la TV",
   explanation:"Mettendo 'spiegazione+から' all'inizio, la frase si legge come 'perciò/quindi', più vicina all'ordine naturale italiano."},
  {lesson:9, point:"から: spiegazione prima della situazione", type:"choose_question_word",
   prompt:"Quale ordine mette la SPIEGAZIONE prima della SITUAZIONE?",
   options:["spiegazione + から、situazione。", "situazione。spiegazione + から。", "situazione + から、spiegazione。", "Sono equivalenti solo se si usa と"],
   correct:"spiegazione + から、situazione。",
   explanation:"Questo ordine corrisponde a 'perciò/quindi' in italiano, mentre l'ordine opposto (situazione prima) corrisponde a 'perché'."}
];

const GRAMMAR_L10 = [
  {lesson:10, point:"Comparazione tra due elementi", type:"translate_jp_it",
   prompt:"中国（ちゅうごく）のほうが日本（にほん）より大きいです（おおきいです）。",
   options:["La Cina è più grande del Giappone", "Il Giappone è più grande della Cina", "La Cina è grande quanto il Giappone", "Il Giappone è il più grande"],
   correct:"La Cina è più grande del Giappone",
   explanation:"Struttura: AのほうがBより(proprietà) = 'A è più (proprietà) di B'. のほうが segna l'elemento superiore, より quello di paragone."},
  {lesson:10, point:"Comparazione tra due elementi", type:"translate_it_jp",
   prompt:"Come chiedi 'Cosa è più freddo, il Giappone o il Canada?'",
   options:["日本（にほん）とカナダとどちらのほうが寒いです（さむいです）か。", "日本（にほん）はカナダより寒いです（さむいです）か。", "どちらが日本（にほん）とカナダですか。", "日本（にほん）とカナダが寒いです（さむいです）。"],
   correct:"日本（にほん）とカナダとどちらのほうが寒いです（さむいです）か。",
   explanation:"Per confrontare due elementi in una domanda: AとBとどちらのほうが(proprietà)ですか。"},
  {lesson:10, point:"Comparazione tra tre o più elementi", type:"translate_jp_it",
   prompt:"秋（あき）がいちばん好きです（すきです）。",
   options:["L'autunno mi piace più di tutti", "Non mi piace affatto l'autunno", "L'autunno è la prima stagione", "Preferisco l'autunno all'estate"],
   correct:"L'autunno mi piace più di tutti",
   explanation:"いちばん (il più) si usa per confronti tra tre o più elementi, mentre のほう si usa solo tra due."},
  {lesson:10, point:"Comparazione tra tre o più elementi", type:"spot_error",
   prompt:"Quale frase è sbagliata? (confronto tra tre nazioni)",
   options:["カナダとフランスと日本（にほん）の中で（なかで）、どこのほうが寒いです（さむいです）か。", "カナダとフランスと日本（にほん）の中で（なかで）、どこがいちばん寒いです（さむいです）か。", "カナダがいちばん寒い（さむい）と思います（おもいます）。", "季節（きせつ）の中で（なかで）いつがいちばん好きです（すきです）か。"],
   correct:"カナダとフランスと日本（にほん）の中で（なかで）、どこのほうが寒いです（さむいです）か。",
   explanation:"のほう si usa solo per confronti tra DUE elementi; con tre o più si usa いちばん, non のほう."},
  {lesson:10, point:"Aggettivo／Nome + の (pronome indefinito)", type:"translate_jp_it",
   prompt:"私（わたし）は黒い（くろい）セーターを持っています（もっています）。赤い（あかい）のも持っています（もっています）。",
   options:["Ho un maglione nero. Ne ho anche uno rosso.", "Ho un maglione nero e rosso.", "Il mio maglione nero è diventato rosso.", "Non ho maglioni rossi."],
   correct:"Ho un maglione nero. Ne ho anche uno rosso.",
   explanation:"の sostituisce un nome già menzionato (セーター) per evitare di ripeterlo: '赤い（あかい）の' = 'quello rosso'."},
  {lesson:10, point:"Aggettivo／Nome + の (pronome indefinito)", type:"translate_it_jp",
   prompt:"Come dici 'Non è il mio; è di Mary' (parlando di una borsa già menzionata)?",
   options:["私（わたし）のじゃないです。メアリーさんのです。", "私（わたし）はじゃないです。メアリーさんはです。", "私（わたし）のかばんじゃないです。メアリーさんのかばんです。(entrambe corrette, ma...)", "私（わたし）のはじゃないです。メアリーさんのはです。"],
   correct:"私（わたし）のじゃないです。メアリーさんのです。",
   explanation:"の dopo un nome/pronome può significare anche 'il/la ... di qualcuno', evitando di ripetere l'oggetto (かばん)."},
  {lesson:10, point:"どこかに／どこにも (estensione di 何か（なにか）／何も（なにも）)", type:"fill_answer",
   prompt:"A: どこ___ 行きましたか（いきましたか）。 B: いいえ、どこ___も 行きませんでした（いきませんでした）。",
   options:["へ／へ", "が／が", "を／を", "の／の"],
   correct:"へ／へ",
   explanation:"どこか/どこも richiedono comunque le particelle non-base come へ, に, で — solo は/が/を vengono omesse."},
  {lesson:10, point:"どこかに／どこにも (estensione di 何か（なにか）／何も（なにも）)", type:"translate_jp_it",
   prompt:"だれかに会いましたか（あいましたか）。",
   options:["Hai visto qualcuno?", "Hai visto tutti?", "Chi hai visto?", "Non hai visto nessuno?"],
   correct:"Hai visto qualcuno?",
   explanation:"だれか = 'qualcuno' (positivo/domanda); だれも + negativo = 'nessuno'."},
  {lesson:10, point:"で (mezzo/strumento)", type:"particle",
   prompt:"バス ___ 駅（えき）まで行きました（いきました）。",
   options:["で", "に", "を", "が"],
   correct:"で",
   explanation:"で indica il mezzo di trasporto o lo strumento usato per fare qualcosa: 'in autobus'."},
  {lesson:10, point:"で (mezzo/strumento)", type:"translate_jp_it",
   prompt:"はしでご飯（ごはん）を食べます（たべます）。",
   options:["Mangio il riso con le bacchette", "Mangio riso e bacchette", "Le bacchette sono per il riso", "Compro le bacchette per il riso"],
   correct:"Mangio il riso con le bacchette",
   explanation:"で dopo uno strumento (はし = bacchette) significa 'con, usando quello strumento'."}
];

// Pool combinato di tutte le domande di grammatica (tutte le lezioni 1-10, esclusa la coniugazione di verbi/aggettivi)
const GRAMMAR_L11 = [
  {lesson:11, point:"〜たい (volere fare)", type:"translate_jp_it",
   prompt:"今度（こんど）の週末（しゅうまつ）は、映画（えいが）を見たい（みたい）です。",
   options:["Questo fine settimana voglio vedere un film", "Questo fine settimana ho visto un film", "Questo fine settimana devo vedere un film", "Questo fine settimana non voglio vedere un film"],
   correct:"Questo fine settimana voglio vedere un film",
   explanation:"Radice del verbo (forma prima di ます) + たいです esprime un desiderio: 'voglio fare...'"},
  {lesson:11, point:"〜たい (volere fare)", type:"translate_jp_it",
   prompt:"あの人（ひと）には会いたく（あいたく）ないです。",
   options:["Non voglio vedere quella persona", "Voglio vedere quella persona", "Non ho visto quella persona", "Quella persona non vuole vedermi"],
   correct:"Non voglio vedere quella persona",
   explanation:"たい si coniuga come un い-aggettivo: la forma negativa è たくないです."},
  {lesson:11, point:"〜たり〜たりする (fare cose come...)", type:"translate_jp_it",
   prompt:"週末（しゅうまつ）は、勉強したり（べんきょうしたり）、友だち（ともだち）と話したり（はなしたり）しました。",
   options:["Nel weekend ho fatto cose come studiare e parlare con amici", "Nel weekend ho solo studiato", "Nel weekend studierò e parlerò con amici", "Nel weekend non ho studiato né parlato con amici"],
   correct:"Nel weekend ho fatto cose come studiare e parlare con amici",
   explanation:"〜たり〜たりする elenca alcune attività come esempi, senza un ordine preciso né escludere altre attività."},
  {lesson:11, point:"〜たり〜たりする (fare cose come...)", type:"translate_jp_it",
   prompt:"踊ったり（おどったり）、音楽（おんがく）を聞いたり（きいたり）するのが好きです（すきです）。",
   options:["Mi piace fare cose come ballare e ascoltare musica", "Mi piace solo ballare", "Non mi piace ballare né ascoltare musica", "Ho ballato e ascoltato musica ieri"],
   correct:"Mi piace fare cose come ballare e ascoltare musica",
   explanation:"Come sopra: elenca esempi di attività gradite, non una lista esaustiva."},
  {lesson:11, point:"〜ことがある (avere esperienza di...)", type:"translate_jp_it",
   prompt:"富士山（ふじさん）に登った（のぼった）ことがあります。",
   options:["Ho avuto l'esperienza di scalare il Monte Fuji", "Sto scalando il Monte Fuji", "Scalerò il Monte Fuji", "Non ho mai scalato il Monte Fuji"],
   correct:"Ho avuto l'esperienza di scalare il Monte Fuji",
   explanation:"Forma breve passata del verbo + ことがある descrive un'esperienza avuta in passato."},
  {lesson:11, point:"〜ことがある (avere esperienza di...)", type:"translate_jp_it",
   prompt:"たけしさんは授業（じゅぎょう）を休んだ（やすんだ）ことがありません。",
   options:["Takeshi non è mai stato assente da una lezione", "Takeshi è stato assente da una lezione", "Takeshi sarà assente da una lezione", "Takeshi odia le lezioni"],
   correct:"Takeshi non è mai stato assente da una lezione",
   explanation:"La forma negativa ことがありません indica che quell'esperienza non è mai avvenuta."},
  {lesson:11, point:"Noun A や Noun B", type:"particle",
   prompt:"京都（きょうと）___奈良（なら）に行きました（いきました）。",
   options:["や", "と", "か", "の"],
   correct:"や",
   explanation:"や collega nomi come esempi non esaustivi: 'sono andato a Kyoto e Nara, tra gli altri posti'."},
  {lesson:11, point:"Noun A や Noun B", type:"translate_jp_it",
   prompt:"京都（きょうと）や奈良（なら）に行きました（いきました）。",
   options:["Sono andato a Kyoto e Nara, e forse anche altrove", "Sono andato solo a Kyoto e Nara, nient'altro", "Andrò a Kyoto o a Nara", "Kyoto e Nara sono vicine"],
   correct:"Sono andato a Kyoto e Nara, e forse anche altrove",
   explanation:"A differenza di と (lista completa), や suggerisce che l'elenco è solo esemplificativo."}
];

const GRAMMAR_L12 = [
  {lesson:12, point:"〜んです (spiegare una situazione)", type:"translate_jp_it",
   prompt:"バスが来なかった（こなかった）んです。",
   options:["È che l'autobus non è arrivato (ecco perché)", "L'autobus non arriverà", "L'autobus arriva sempre in orario", "Non prendo mai l'autobus"],
   correct:"È che l'autobus non è arrivato (ecco perché)",
   explanation:"んです collega un fatto a una spiegazione per la situazione in corso — qui, il motivo del ritardo."},
  {lesson:12, point:"〜んです (spiegare una situazione)", type:"transform",
   prompt:"Come diventa una spiegazione (〜んです) la frase 「学生（がくせい）です」?",
   options:["学生（がくせい）なんです", "学生（がくせい）んです", "学生（がくせい）だんです", "学生（がくせい）のです"],
   correct:"学生なんです",
   explanation:"Dopo un nome o un な-aggettivo al presente affermativo, な si inserisce prima di んです."},
  {lesson:12, point:"〜すぎる (troppo)", type:"translate_jp_it",
   prompt:"この本（ほん）は高すぎます（たかすぎます）。",
   options:["Questo libro è troppo caro", "Questo libro è economico", "Questo libro non è caro", "Questo libro è il più caro"],
   correct:"Questo libro è troppo caro",
   explanation:"Radice dell'aggettivo/verbo + すぎる indica un eccesso: 'troppo...'."},
  {lesson:12, point:"〜すぎる (troppo)", type:"translate_jp_it",
   prompt:"食べすぎては（たべすぎては）いけません。",
   options:["Non devi mangiare troppo", "Devi mangiare di più", "Non hai mangiato abbastanza", "Devi smettere di mangiare"],
   correct:"Non devi mangiare troppo",
   explanation:"食べすぎる = 'mangiare troppo'; qui combinato con てはいけません (non devi/non puoi)."},
  {lesson:12, point:"〜ほうがいいです (è meglio)", type:"translate_jp_it",
   prompt:"もっと野菜（やさい）を食べた（たべた）ほうがいいですよ。",
   options:["Sarebbe meglio mangiare più verdure", "Non dovresti mangiare verdure", "Hai mangiato troppe verdure", "Le verdure sono più economiche"],
   correct:"Sarebbe meglio mangiare più verdure",
   explanation:"Forma breve passata affermativa + ほうがいいです dà un consiglio positivo."},
  {lesson:12, point:"〜ほうがいいです (è meglio)", type:"translate_jp_it",
   prompt:"授業（じゅぎょう）を休まない（やすまない）ほうがいいですよ。",
   options:["Sarebbe meglio non saltare le lezioni", "Sarebbe meglio saltare le lezioni", "Hai saltato le lezioni", "Le lezioni sono state annullate"],
   correct:"Sarebbe meglio non saltare le lezioni",
   explanation:"Per un consiglio negativo si usa la forma breve presente negativa + ほうがいいです."},
  {lesson:12, point:"〜ので (perché, più formale di から)", type:"translate_jp_it",
   prompt:"宿題（しゅくだい）がたくさんあったので、きのうの夜（よる）、寝ませんでした（ねませんでした）。",
   options:["Non ho dormito ieri notte perché avevo molti compiti", "Ho dormito molto ieri notte", "Avevo pochi compiti ieri", "Dormirò molto stanotte"],
   correct:"Non ho dormito ieri notte perché avevo molti compiti",
   explanation:"ので introduce la ragione, in modo simile a から ma più formale."},
  {lesson:12, point:"〜ので (perché, più formale di から)", type:"fill_answer",
   prompt:"今日（きょう）は日曜日（にちようび）___、銀行（ぎんこう）は休み（やすみ）です。 (con un nome, servono forma な)",
   options:["なので", "ので", "だので", "のので"],
   correct:"なので",
   explanation:"Dopo un nome (o な-aggettivo) al presente affermativo, な si inserisce prima di ので, proprio come per んです."},
  {lesson:12, point:"〜なければいけません (dovere)", type:"translate_jp_it",
   prompt:"試験（しけん）があるから、勉強しなければ（べんきょうしなければ）いけません。",
   options:["Devo studiare perché c'è un esame", "Non devo studiare, non c'è esame", "Ho già studiato per l'esame", "Non voglio studiare"],
   correct:"Devo studiare perché c'è un esame",
   explanation:"なければいけません (o la variante colloquiale なきゃいけません) esprime un obbligo: 'devo fare...'."},
  {lesson:12, point:"〜なければいけません (dovere)", type:"translate_jp_it",
   prompt:"けさは、六時（ろくじ）に起きなきゃ（おきなきゃ）いけませんでした。",
   options:["Stamattina ho dovuto alzarmi alle sei", "Stamattina mi sono alzato tardi", "Domani devo alzarmi alle sei", "Non ho dovuto alzarmi presto"],
   correct:"Stamattina ho dovuto alzarmi alle sei",
   explanation:"なきゃいけませんでした è la versione colloquiale e passata di 'dovevo fare...'."},
  {lesson:12, point:"〜でしょうか (forse...? in modo garbato)", type:"translate_jp_it",
   prompt:"あした、雨（あめ）が降る（ふる）でしょうか。",
   options:["Pioverà domani, secondo te?", "Sta piovendo ora", "Ieri è piovuto", "Non pioverà mai"],
   correct:"Pioverà domani, secondo te?",
   explanation:"でしょうか aggiunge un tono garbato e dubbioso a una domanda, invitando l'opinione dell'ascoltatore."},
  {lesson:12, point:"〜でしょうか (forse...? in modo garbato)", type:"choose_question_word",
   prompt:"Perché si usa でしょうか invece di ですか in una domanda?",
   options:["Per renderla più garbata e meno diretta", "Per renderla più aggressiva", "Per parlare al passato", "Per negare la domanda"],
   correct:"Per renderla più garbata e meno diretta",
   explanation:"でしょうか implica che pensi che l'ascoltatore abbia un'opinione più informata, evitando di metterlo in imbarazzo."}
];

// Pool combinato di tutte le domande di grammatica (Lezioni 1-12, esclusa la coniugazione di verbi/aggettivi)
const GRAMMAR_ALL = [...GRAMMAR_L1, ...GRAMMAR_L2, ...GRAMMAR_L3, ...GRAMMAR_L4, ...GRAMMAR_L5, ...GRAMMAR_L6, ...GRAMMAR_L7, ...GRAMMAR_L8, ...GRAMMAR_L9, ...GRAMMAR_L10, ...GRAMMAR_L11, ...GRAMMAR_L12];
