// Database verbi e aggettivi Genki I - Lezioni 3-10, con coniugazioni precalcolate
// type verbi: 'ru' | 'u' | 'irr'   |   type aggettivi: 'i' | 'na'
// forms verbi: masu, masen, mashita, masendeshita, te, ta
// forms aggettivi: pres_aff, pres_neg, past_aff, past_neg, te

const VERBS_ALL = [
  {jp:"いく", kanji:"行く", type:"u", it:"andare", forms:{masu:"いきます", masen:"いきません", mashita:"いきました", masendeshita:"いきませんでした", te:"いって", ta:"いった"}},
  {jp:"かえる", kanji:"帰る", type:"u", it:"tornare", forms:{masu:"かえります", masen:"かえりません", mashita:"かえりました", masendeshita:"かえりませんでした", te:"かえって", ta:"かえった"}},
  {jp:"きく", kanji:"聞く", type:"u", it:"ascoltare", forms:{masu:"ききます", masen:"ききません", mashita:"ききました", masendeshita:"ききませんでした", te:"きいて", ta:"きいた"}},
  {jp:"のむ", kanji:"飲む", type:"u", it:"bere", forms:{masu:"のみます", masen:"のみません", mashita:"のみました", masendeshita:"のみませんでした", te:"のんで", ta:"のんだ"}},
  {jp:"はなす", kanji:"話す", type:"u", it:"parlare", forms:{masu:"はなします", masen:"はなしません", mashita:"はなしました", masendeshita:"はなしませんでした", te:"はなして", ta:"はなした"}},
  {jp:"よむ", kanji:"読む", type:"u", it:"leggere", forms:{masu:"よみます", masen:"よみません", mashita:"よみました", masendeshita:"よみませんでした", te:"よんで", ta:"よんだ"}},
  {jp:"おきる", kanji:"起きる", type:"ru", it:"alzarsi", forms:{masu:"おきます", masen:"おきません", mashita:"おきました", masendeshita:"おきませんでした", te:"おきて", ta:"おきた"}},
  {jp:"たべる", kanji:"食べる", type:"ru", it:"mangiare", forms:{masu:"たべます", masen:"たべません", mashita:"たべました", masendeshita:"たべませんでした", te:"たべて", ta:"たべた"}},
  {jp:"ねる", kanji:"寝る", type:"ru", it:"dormire; andare a letto", forms:{masu:"ねます", masen:"ねません", mashita:"ねました", masendeshita:"ねませんでした", te:"ねて", ta:"ねた"}},
  {jp:"みる", kanji:"見る", type:"ru", it:"vedere; guardare", forms:{masu:"みます", masen:"みません", mashita:"みました", masendeshita:"みませんでした", te:"みて", ta:"みた"}},
  {jp:"くる", kanji:"来る", type:"irr", it:"venire", forms:{masu:"きます", masen:"きません", mashita:"きました", masendeshita:"きませんでした", te:"きて", ta:"きた"}},
  {jp:"する", kanji:null, type:"irr", it:"fare", forms:{masu:"します", masen:"しません", mashita:"しました", masendeshita:"しませんでした", te:"して", ta:"した"}},
  {jp:"べんきょうする", kanji:"勉強する", type:"irr", it:"studiare", forms:{masu:"べんきょうします", masen:"べんきょうしません", mashita:"べんきょうしました", masendeshita:"べんきょうしませんでした", te:"べんきょうして", ta:"べんきょうした"}},
  {jp:"あう", kanji:"会う", type:"u", it:"incontrare", forms:{masu:"あいます", masen:"あいません", mashita:"あいました", masendeshita:"あいませんでした", te:"あって", ta:"あった"}},
  {jp:"ある", kanji:null, type:"u", it:"esserci (cose)", forms:{masu:"あります", masen:"ありません", mashita:"ありました", masendeshita:"ありませんでした", te:"あって", ta:"あった"}},
  {jp:"かう", kanji:"買う", type:"u", it:"comprare", forms:{masu:"かいます", masen:"かいません", mashita:"かいました", masendeshita:"かいませんでした", te:"かって", ta:"かった"}},
  {jp:"かく", kanji:"書く", type:"u", it:"scrivere", forms:{masu:"かきます", masen:"かきません", mashita:"かきました", masendeshita:"かきませんでした", te:"かいて", ta:"かいた"}},
  {jp:"とる", kanji:"撮る", type:"u", it:"scattare (foto)", forms:{masu:"とります", masen:"とりません", mashita:"とりました", masendeshita:"とりませんでした", te:"とって", ta:"とった"}},
  {jp:"まつ", kanji:"待つ", type:"u", it:"aspettare", forms:{masu:"まちます", masen:"まちません", mashita:"まちました", masendeshita:"まちませんでした", te:"まって", ta:"まった"}},
  {jp:"わかる", kanji:null, type:"u", it:"capire", forms:{masu:"わかります", masen:"わかりません", mashita:"わかりました", masendeshita:"わかりませんでした", te:"わかって", ta:"わかった"}},
  {jp:"いる", kanji:null, type:"ru", it:"esserci (persone/animali)", forms:{masu:"います", masen:"いません", mashita:"いました", masendeshita:"いませんでした", te:"いて", ta:"いた"}},
  {jp:"およぐ", kanji:"泳ぐ", type:"u", it:"nuotare", forms:{masu:"およぎます", masen:"およぎません", mashita:"およぎました", masendeshita:"およぎませんでした", te:"およいで", ta:"およいだ"}},
  {jp:"のる", kanji:"乗る", type:"u", it:"salire su (mezzo)", forms:{masu:"のります", masen:"のりません", mashita:"のりました", masendeshita:"のりませんでした", te:"のって", ta:"のった"}},
  {jp:"やる", kanji:null, type:"u", it:"fare", forms:{masu:"やります", masen:"やりません", mashita:"やりました", masendeshita:"やりませんでした", te:"やって", ta:"やった"}},
  {jp:"でかける", kanji:"出かける", type:"ru", it:"uscire", forms:{masu:"でかけます", masen:"でかけません", mashita:"でかけました", masendeshita:"でかけませんでした", te:"でかけて", ta:"でかけた"}},
  {jp:"あそぶ", kanji:"遊ぶ", type:"u", it:"giocare", forms:{masu:"あそびます", masen:"あそびません", mashita:"あそびました", masendeshita:"あそびませんでした", te:"あそんで", ta:"あそんだ"}},
  {jp:"いそぐ", kanji:"急ぐ", type:"u", it:"affrettarsi", forms:{masu:"いそぎます", masen:"いそぎません", mashita:"いそぎました", masendeshita:"いそぎませんでした", te:"いそいで", ta:"いそいだ"}},
  {jp:"かえす", kanji:"返す", type:"u", it:"restituire", forms:{masu:"かえします", masen:"かえしません", mashita:"かえしました", masendeshita:"かえしませんでした", te:"かえして", ta:"かえした"}},
  {jp:"けす", kanji:"消す", type:"u", it:"spegnere; cancellare", forms:{masu:"けします", masen:"けしません", mashita:"けしました", masendeshita:"けしませんでした", te:"けして", ta:"けした"}},
  {jp:"しぬ", kanji:"死ぬ", type:"u", it:"morire", forms:{masu:"しにます", masen:"しにません", mashita:"しにました", masendeshita:"しにませんでした", te:"しんで", ta:"しんだ"}},
  {jp:"すわる", kanji:"座る", type:"u", it:"sedersi", forms:{masu:"すわります", masen:"すわりません", mashita:"すわりました", masendeshita:"すわりませんでした", te:"すわって", ta:"すわった"}},
  {jp:"たつ", kanji:"立つ", type:"u", it:"alzarsi in piedi", forms:{masu:"たちます", masen:"たちません", mashita:"たちました", masendeshita:"たちませんでした", te:"たって", ta:"たった"}},
  {jp:"つかう", kanji:"使う", type:"u", it:"usare", forms:{masu:"つかいます", masen:"つかいません", mashita:"つかいました", masendeshita:"つかいませんでした", te:"つかって", ta:"つかった"}},
  {jp:"てつだう", kanji:"手伝う", type:"u", it:"aiutare", forms:{masu:"てつだいます", masen:"てつだいません", mashita:"てつだいました", masendeshita:"てつだいませんでした", te:"てつだって", ta:"てつだった"}},
  {jp:"はいる", kanji:"入る", type:"u", it:"entrare", forms:{masu:"はいります", masen:"はいりません", mashita:"はいりました", masendeshita:"はいりませんでした", te:"はいって", ta:"はいった"}},
  {jp:"もつ", kanji:"持つ", type:"u", it:"portare; tenere", forms:{masu:"もちます", masen:"もちません", mashita:"もちました", masendeshita:"もちませんでした", te:"もって", ta:"もった"}},
  {jp:"やすむ", kanji:"休む", type:"u", it:"riposare; assentarsi", forms:{masu:"やすみます", masen:"やすみません", mashita:"やすみました", masendeshita:"やすみませんでした", te:"やすんで", ta:"やすんだ"}},
  {jp:"あける", kanji:"開ける", type:"ru", it:"aprire", forms:{masu:"あけます", masen:"あけません", mashita:"あけました", masendeshita:"あけませんでした", te:"あけて", ta:"あけた"}},
  {jp:"しめる", kanji:"閉める", type:"ru", it:"chiudere", forms:{masu:"しめます", masen:"しめません", mashita:"しめました", masendeshita:"しめませんでした", te:"しめて", ta:"しめた"}},
  {jp:"おしえる", kanji:"教える", type:"ru", it:"insegnare", forms:{masu:"おしえます", masen:"おしえません", mashita:"おしえました", masendeshita:"おしえませんでした", te:"おしえて", ta:"おしえた"}},
  {jp:"わすれる", kanji:"忘れる", type:"ru", it:"dimenticare", forms:{masu:"わすれます", masen:"わすれません", mashita:"わすれました", masendeshita:"わすれませんでした", te:"わすれて", ta:"わすれた"}},
  {jp:"おりる", kanji:"降りる", type:"ru", it:"scendere", forms:{masu:"おります", masen:"おりません", mashita:"おりました", masendeshita:"おりませんでした", te:"おりて", ta:"おりた"}},
  {jp:"かりる", kanji:"借りる", type:"ru", it:"prendere in prestito", forms:{masu:"かります", masen:"かりません", mashita:"かりました", masendeshita:"かりませんでした", te:"かりて", ta:"かりた"}},
  {jp:"つける", kanji:null, type:"ru", it:"accendere", forms:{masu:"つけます", masen:"つけません", mashita:"つけました", masendeshita:"つけませんでした", te:"つけて", ta:"つけた"}},
  {jp:"でんわする", kanji:"電話する", type:"irr", it:"telefonare", forms:{masu:"でんわします", masen:"でんわしません", mashita:"でんわしました", masendeshita:"でんわしませんでした", te:"でんわして", ta:"でんわした"}},
  {jp:"つれてくる", kanji:"連れてくる", type:"irr", it:"portare (una persona)", forms:{masu:"つれてきます", masen:"つれてきません", mashita:"つれてきました", masendeshita:"つれてきませんでした", te:"つれてきて", ta:"つれてきた"}},
  {jp:"もってくる", kanji:"持ってくる", type:"irr", it:"portare (una cosa)", forms:{masu:"もってきます", masen:"もってきません", mashita:"もってきました", masendeshita:"もってきませんでした", te:"もってきて", ta:"もってきた"}},
  {jp:"うたう", kanji:"歌う", type:"u", it:"cantare", forms:{masu:"うたいます", masen:"うたいません", mashita:"うたいました", masendeshita:"うたいませんでした", te:"うたって", ta:"うたった"}},
  {jp:"かぶる", kanji:null, type:"u", it:"indossare (cappello)", forms:{masu:"かぶります", masen:"かぶりません", mashita:"かぶりました", masendeshita:"かぶりませんでした", te:"かぶって", ta:"かぶった"}},
  {jp:"はく", kanji:null, type:"u", it:"indossare (sotto la vita)", forms:{masu:"はきます", masen:"はきません", mashita:"はきました", masendeshita:"はきませんでした", te:"はいて", ta:"はいた"}},
  {jp:"しる", kanji:"知る", type:"u", it:"conoscere; sapere", forms:{masu:"しります", masen:"しりません", mashita:"しりました", masendeshita:"しりませんでした", te:"しって", ta:"しった"}},
  {jp:"すむ", kanji:"住む", type:"u", it:"vivere; abitare", forms:{masu:"すみます", masen:"すみません", mashita:"すみました", masendeshita:"すみませんでした", te:"すんで", ta:"すんだ"}},
  {jp:"はたらく", kanji:"働く", type:"u", it:"lavorare", forms:{masu:"はたらきます", masen:"はたらきません", mashita:"はたらきました", masendeshita:"はたらきませんでした", te:"はたらいて", ta:"はたらいた"}},
  {jp:"ふとる", kanji:"太る", type:"u", it:"ingrassare", forms:{masu:"ふとります", masen:"ふとりません", mashita:"ふとりました", masendeshita:"ふとりませんでした", te:"ふとって", ta:"ふとった"}},
  {jp:"かける", kanji:null, type:"ru", it:"indossare (occhiali)", forms:{masu:"かけます", masen:"かけません", mashita:"かけました", masendeshita:"かけませんでした", te:"かけて", ta:"かけた"}},
  {jp:"きる", kanji:"着る", type:"ru", it:"indossare (sopra la vita)", forms:{masu:"きます", masen:"きません", mashita:"きました", masendeshita:"きませんでした", te:"きて", ta:"きた"}},
  {jp:"やせる", kanji:null, type:"ru", it:"dimagrire", forms:{masu:"やせます", masen:"やせません", mashita:"やせました", masendeshita:"やせませんでした", te:"やせて", ta:"やせた"}},
  {jp:"けっこんする", kanji:"結婚する", type:"irr", it:"sposarsi", forms:{masu:"けっこんします", masen:"けっこんしません", mashita:"けっこんしました", masendeshita:"けっこんしませんでした", te:"けっこんして", ta:"けっこんした"}},
  {jp:"あらう", kanji:"洗う", type:"u", it:"lavare", forms:{masu:"あらいます", masen:"あらいません", mashita:"あらいました", masendeshita:"あらいませんでした", te:"あらって", ta:"あらった"}},
  {jp:"いう", kanji:"言う", type:"u", it:"dire", forms:{masu:"いいます", masen:"いいません", mashita:"いいました", masendeshita:"いいませんでした", te:"いって", ta:"いった"}},
  {jp:"いる", kanji:null, type:"u", it:"servire; necessitare (要る)", forms:{masu:"いります", masen:"いりません", mashita:"いりました", masendeshita:"いりませんでした", te:"いって", ta:"いった"}},
  {jp:"おそくなる", kanji:"遅くなる", type:"u", it:"fare tardi", forms:{masu:"おそくなります", masen:"おそくなりません", mashita:"おそくなりました", masendeshita:"おそくなりませんでした", te:"おそくなって", ta:"おそくなった"}},
  {jp:"おもう", kanji:"思う", type:"u", it:"pensare", forms:{masu:"おもいます", masen:"おもいません", mashita:"おもいました", masendeshita:"おもいませんでした", te:"おもって", ta:"おもった"}},
  {jp:"きる", kanji:"切る", type:"u", it:"tagliare", forms:{masu:"きります", masen:"きりません", mashita:"きりました", masendeshita:"きりませんでした", te:"きって", ta:"きった"}},
  {jp:"つくる", kanji:"作る", type:"u", it:"fare; creare", forms:{masu:"つくります", masen:"つくりません", mashita:"つくりました", masendeshita:"つくりませんでした", te:"つくって", ta:"つくった"}},
  {jp:"ふる", kanji:null, type:"u", it:"piovere/nevicare", forms:{masu:"ふります", masen:"ふりません", mashita:"ふりました", masendeshita:"ふりませんでした", te:"ふって", ta:"ふった"}},
  {jp:"もっていく", kanji:"持っていく", type:"u", it:"portare (una cosa)", forms:{masu:"もっていきます", masen:"もっていきません", mashita:"もっていきました", masendeshita:"もっていきませんでした", te:"もっていいて", ta:"もっていいた"}},
  {jp:"すてる", kanji:"捨てる", type:"ru", it:"buttare via", forms:{masu:"すてます", masen:"すてません", mashita:"すてました", masendeshita:"すてませんでした", te:"すてて", ta:"すてた"}},
  {jp:"はじめる", kanji:"始める", type:"ru", it:"iniziare", forms:{masu:"はじめます", masen:"はじめません", mashita:"はじめました", masendeshita:"はじめませんでした", te:"はじめて", ta:"はじめた"}},
  {jp:"うんてんする", kanji:"運転する", type:"irr", it:"guidare", forms:{masu:"うんてんします", masen:"うんてんしません", mashita:"うんてんしました", masendeshita:"うんてんしませんでした", te:"うんてんして", ta:"うんてんした"}},
  {jp:"せんたくする", kanji:"洗濯する", type:"irr", it:"fare il bucato", forms:{masu:"せんたくします", masen:"せんたくしません", mashita:"せんたくしました", masendeshita:"せんたくしませんでした", te:"せんたくして", ta:"せんたくした"}},
  {jp:"そうじする", kanji:"掃除する", type:"irr", it:"pulire", forms:{masu:"そうじします", masen:"そうじしません", mashita:"そうじしました", masendeshita:"そうじしませんでした", te:"そうじして", ta:"そうじした"}},
  {jp:"りょうりする", kanji:"料理する", type:"irr", it:"cucinare", forms:{masu:"りょうりします", masen:"りょうりしません", mashita:"りょうりしました", masendeshita:"りょうりしませんでした", te:"りょうりして", ta:"りょうりした"}},
  {jp:"おどる", kanji:"踊る", type:"u", it:"ballare", forms:{masu:"おどります", masen:"おどりません", mashita:"おどりました", masendeshita:"おどりませんでした", te:"おどって", ta:"おどった"}},
  {jp:"おわる", kanji:"終わる", type:"u", it:"finire", forms:{masu:"おわります", masen:"おわりません", mashita:"おわりました", masendeshita:"おわりませんでした", te:"おわって", ta:"おわった"}},
  {jp:"はじまる", kanji:"始まる", type:"u", it:"iniziare (qualcosa)", forms:{masu:"はじまります", masen:"はじまりません", mashita:"はじまりました", masendeshita:"はじまりませんでした", te:"はじまって", ta:"はじまった"}},
  {jp:"ひく", kanji:"弾く", type:"u", it:"suonare (strumento)", forms:{masu:"ひきます", masen:"ひきません", mashita:"ひきました", masendeshita:"ひきませんでした", te:"ひいて", ta:"ひいた"}},
  {jp:"もらう", kanji:null, type:"u", it:"ricevere", forms:{masu:"もらいます", masen:"もらいません", mashita:"もらいました", masendeshita:"もらいませんでした", te:"もらって", ta:"もらった"}},
  {jp:"おぼえる", kanji:"覚える", type:"ru", it:"memorizzare", forms:{masu:"おぼえます", masen:"おぼえません", mashita:"おぼえました", masendeshita:"おぼえませんでした", te:"おぼえて", ta:"おぼえた"}},
  {jp:"でる", kanji:"出る", type:"ru", it:"uscire; partecipare", forms:{masu:"でます", masen:"でません", mashita:"でました", masendeshita:"でませんでした", te:"でて", ta:"でた"}},
  {jp:"うんどうする", kanji:"運動する", type:"irr", it:"fare esercizio", forms:{masu:"うんどうします", masen:"うんどうしません", mashita:"うんどうしました", masendeshita:"うんどうしませんでした", te:"うんどうして", ta:"うんどうした"}},
  {jp:"さんぽする", kanji:"散歩する", type:"irr", it:"fare una passeggiata", forms:{masu:"さんぽします", masen:"さんぽしません", mashita:"さんぽしました", masendeshita:"さんぽしませんでした", te:"さんぽして", ta:"さんぽした"}},
  {jp:"かかる", kanji:null, type:"u", it:"richiedere (tempo/denaro)", forms:{masu:"かかります", masen:"かかりません", mashita:"かかりました", masendeshita:"かかりませんでした", te:"かかって", ta:"かかった"}},
  {jp:"とまる", kanji:"泊まる", type:"u", it:"alloggiare", forms:{masu:"とまります", masen:"とまりません", mashita:"とまりました", masendeshita:"とまりませんでした", te:"とまって", ta:"とまった"}},
  {jp:"なる", kanji:null, type:"u", it:"diventare", forms:{masu:"なります", masen:"なりません", mashita:"なりました", masendeshita:"なりませんでした", te:"なって", ta:"なった"}},
  {jp:"きめる", kanji:"決める", type:"ru", it:"decidere", forms:{masu:"きめます", masen:"きめません", mashita:"きめました", masendeshita:"きめませんでした", te:"きめて", ta:"きめた"}},
  {jp:"りょこうする", kanji:"旅行する", type:"irr", it:"viaggiare", forms:{masu:"りょこうします", masen:"りょこうしません", mashita:"りょこうしました", masendeshita:"りょこうしませんでした", te:"りょこうして", ta:"りょこうした"}},
  {jp:"れんしゅうする", kanji:"練習する", type:"irr", it:"esercitarsi", forms:{masu:"れんしゅうします", masen:"れんしゅうしません", mashita:"れんしゅうしました", masendeshita:"れんしゅうしませんでした", te:"れんしゅうして", ta:"れんしゅうした"}}
];

const ADJECTIVES_ALL = [
  {jp:"はやい", kanji:"早い", type:"i", it:"presto", forms:{pres_aff:"はやいです", pres_neg:"はやくないです", past_aff:"はやかったです", past_neg:"はやくなかったです", te:"はやくて"}},
  {jp:"あたらしい", kanji:"新しい", type:"i", it:"nuovo", forms:{pres_aff:"あたらしいです", pres_neg:"あたらしくないです", past_aff:"あたらしかったです", past_neg:"あたらしくなかったです", te:"あたらしくて"}},
  {jp:"ふるい", kanji:"古い", type:"i", it:"vecchio (cose)", forms:{pres_aff:"ふるいです", pres_neg:"ふるくないです", past_aff:"ふるかったです", past_neg:"ふるくなかったです", te:"ふるくて"}},
  {jp:"あつい", kanji:"暑い", type:"i", it:"caldo (tempo)", forms:{pres_aff:"あついです", pres_neg:"あつくないです", past_aff:"あつかったです", past_neg:"あつくなかったです", te:"あつくて"}},
  {jp:"さむい", kanji:"寒い", type:"i", it:"freddo (tempo)", forms:{pres_aff:"さむいです", pres_neg:"さむくないです", past_aff:"さむかったです", past_neg:"さむくなかったです", te:"さむくて"}},
  {jp:"いそがしい", kanji:"忙しい", type:"i", it:"impegnato", forms:{pres_aff:"いそがしいです", pres_neg:"いそがしくないです", past_aff:"いそがしかったです", past_neg:"いそがしくなかったです", te:"いそがしくて"}},
  {jp:"おおきい", kanji:"大きい", type:"i", it:"grande", forms:{pres_aff:"おおきいです", pres_neg:"おおきくないです", past_aff:"おおきかったです", past_neg:"おおきくなかったです", te:"おおきくて"}},
  {jp:"ちいさい", kanji:"小さい", type:"i", it:"piccolo", forms:{pres_aff:"ちいさいです", pres_neg:"ちいさくないです", past_aff:"ちいさかったです", past_neg:"ちいさくなかったです", te:"ちいさくて"}},
  {jp:"おもしろい", kanji:"面白い", type:"i", it:"interessante; divertente", forms:{pres_aff:"おもしろいです", pres_neg:"おもしろくないです", past_aff:"おもしろかったです", past_neg:"おもしろくなかったです", te:"おもしろくて"}},
  {jp:"つまらない", kanji:null, type:"i", it:"noioso", forms:{pres_aff:"つまらないです", pres_neg:"つまらなくないです", past_aff:"つまらなかったです", past_neg:"つまらなくなかったです", te:"つまらなくて"}},
  {jp:"やさしい", kanji:null, type:"i", it:"facile; gentile", forms:{pres_aff:"やさしいです", pres_neg:"やさしくないです", past_aff:"やさしかったです", past_neg:"やさしくなかったです", te:"やさしくて"}},
  {jp:"むずかしい", kanji:"難しい", type:"i", it:"difficile", forms:{pres_aff:"むずかしいです", pres_neg:"むずかしくないです", past_aff:"むずかしかったです", past_neg:"むずかしくなかったです", te:"むずかしくて"}},
  {jp:"こわい", kanji:"怖い", type:"i", it:"spaventoso", forms:{pres_aff:"こわいです", pres_neg:"こわくないです", past_aff:"こわかったです", past_neg:"こわくなかったです", te:"こわくて"}},
  {jp:"たのしい", kanji:"楽しい", type:"i", it:"divertente", forms:{pres_aff:"たのしいです", pres_neg:"たのしくないです", past_aff:"たのしかったです", past_neg:"たのしくなかったです", te:"たのしくて"}},
  {jp:"やすい", kanji:"安い", type:"i", it:"economico", forms:{pres_aff:"やすいです", pres_neg:"やすくないです", past_aff:"やすかったです", past_neg:"やすくなかったです", te:"やすくて"}},
  {jp:"すき", kanji:"好き", type:"na", it:"piacere (amare)", forms:{pres_aff:"すきです", pres_neg:"すきじゃないです", past_aff:"すきでした", past_neg:"すきじゃなかったです", te:"すきで"}},
  {jp:"きらい", kanji:"嫌い", type:"na", it:"non piacere", forms:{pres_aff:"きらいです", pres_neg:"きらいじゃないです", past_aff:"きらいでした", past_neg:"きらいじゃなかったです", te:"きらいで"}},
  {jp:"きれい", kanji:null, type:"na", it:"bello; pulito", forms:{pres_aff:"きれいです", pres_neg:"きれいじゃないです", past_aff:"きれいでした", past_neg:"きれいじゃなかったです", te:"きれいで"}},
  {jp:"げんき", kanji:"元気", type:"na", it:"in salute; energico", forms:{pres_aff:"げんきです", pres_neg:"げんきじゃないです", past_aff:"げんきでした", past_neg:"げんきじゃなかったです", te:"げんきで"}},
  {jp:"しずか", kanji:"静か", type:"na", it:"silenzioso", forms:{pres_aff:"しずかです", pres_neg:"しずかじゃないです", past_aff:"しずかでした", past_neg:"しずかじゃなかったです", te:"しずかで"}},
  {jp:"にぎやか", kanji:null, type:"na", it:"vivace", forms:{pres_aff:"にぎやかです", pres_neg:"にぎやかじゃないです", past_aff:"にぎやかでした", past_neg:"にぎやかじゃなかったです", te:"にぎやかで"}},
  {jp:"ひま", kanji:"暇", type:"na", it:"libero (tempo)", forms:{pres_aff:"ひまです", pres_neg:"ひまじゃないです", past_aff:"ひまでした", past_neg:"ひまじゃなかったです", te:"ひまで"}},
  {jp:"たいへん", kanji:"大変", type:"na", it:"difficile; faticoso", forms:{pres_aff:"たいへんです", pres_neg:"たいへんじゃないです", past_aff:"たいへんでした", past_neg:"たいへんじゃなかったです", te:"たいへんで"}},
  {jp:"ながい", kanji:"長い", type:"i", it:"lungo", forms:{pres_aff:"ながいです", pres_neg:"ながくないです", past_aff:"ながかったです", past_neg:"ながくなかったです", te:"ながくて"}},
  {jp:"みじかい", kanji:"短い", type:"i", it:"corto", forms:{pres_aff:"みじかいです", pres_neg:"みじかくないです", past_aff:"みじかかったです", past_neg:"みじかくなかったです", te:"みじかくて"}},
  {jp:"かわいい", kanji:null, type:"i", it:"carino", forms:{pres_aff:"かわいいです", pres_neg:"かわいくないです", past_aff:"かわいかったです", past_neg:"かわいくなかったです", te:"かわいくて"}},
  {jp:"しんせつ", kanji:"親切", type:"na", it:"gentile", forms:{pres_aff:"しんせつです", pres_neg:"しんせつじゃないです", past_aff:"しんせつでした", past_neg:"しんせつじゃなかったです", te:"しんせつで"}},
  {jp:"べんり", kanji:"便利", type:"na", it:"comodo", forms:{pres_aff:"べんりです", pres_neg:"べんりじゃないです", past_aff:"べんりでした", past_neg:"べんりじゃなかったです", te:"べんりで"}},
  {jp:"じょうず", kanji:"上手", type:"na", it:"bravo", forms:{pres_aff:"じょうずです", pres_neg:"じょうずじゃないです", past_aff:"じょうずでした", past_neg:"じょうずじゃなかったです", te:"じょうずで"}},
  {jp:"へた", kanji:"下手", type:"na", it:"scarso", forms:{pres_aff:"へたです", pres_neg:"へたじゃないです", past_aff:"へたでした", past_neg:"へたじゃなかったです", te:"へたで"}},
  {jp:"ゆうめい", kanji:"有名", type:"na", it:"famoso", forms:{pres_aff:"ゆうめいです", pres_neg:"ゆうめいじゃないです", past_aff:"ゆうめいでした", past_neg:"ゆうめいじゃなかったです", te:"ゆうめいで"}},
  {jp:"あおい", kanji:"青い", type:"i", it:"blu", forms:{pres_aff:"あおいです", pres_neg:"あおくないです", past_aff:"あおかったです", past_neg:"あおくなかったです", te:"あおくて"}},
  {jp:"あかい", kanji:"赤い", type:"i", it:"rosso", forms:{pres_aff:"あかいです", pres_neg:"あかくないです", past_aff:"あかかったです", past_neg:"あかくなかったです", te:"あかくて"}},
  {jp:"くろい", kanji:"黒い", type:"i", it:"nero", forms:{pres_aff:"くろいです", pres_neg:"くろくないです", past_aff:"くろかったです", past_neg:"くろくなかったです", te:"くろくて"}},
  {jp:"しろい", kanji:"白い", type:"i", it:"bianco", forms:{pres_aff:"しろいです", pres_neg:"しろくないです", past_aff:"しろかったです", past_neg:"しろくなかったです", te:"しろくて"}},
  {jp:"さびしい", kanji:"寂しい", type:"i", it:"solo (triste)", forms:{pres_aff:"さびしいです", pres_neg:"さびしくないです", past_aff:"さびしかったです", past_neg:"さびしくなかったです", te:"さびしくて"}},
  {jp:"わかい", kanji:"若い", type:"i", it:"giovane", forms:{pres_aff:"わかいです", pres_neg:"わかくないです", past_aff:"わかかったです", past_neg:"わかくなかったです", te:"わかくて"}},
  {jp:"いじわる", kanji:"意地悪", type:"na", it:"cattivo (di carattere)", forms:{pres_aff:"いじわるです", pres_neg:"いじわるじゃないです", past_aff:"いじわるでした", past_neg:"いじわるじゃなかったです", te:"いじわるで"}},
  {jp:"あたたかい", kanji:"暖かい", type:"i", it:"caldo (tiepido)", forms:{pres_aff:"あたたかいです", pres_neg:"あたたかくないです", past_aff:"あたたかかったです", past_neg:"あたたかくなかったです", te:"あたたかくて"}},
  {jp:"すずしい", kanji:"涼しい", type:"i", it:"fresco", forms:{pres_aff:"すずしいです", pres_neg:"すずしくないです", past_aff:"すずしかったです", past_neg:"すずしくなかったです", te:"すずしくて"}},
  {jp:"つめたい", kanji:"冷たい", type:"i", it:"freddo (cose/persone)", forms:{pres_aff:"つめたいです", pres_neg:"つめたくないです", past_aff:"つめたかったです", past_neg:"つめたくなかったです", te:"つめたくて"}},
  {jp:"おそい", kanji:"遅い", type:"i", it:"lento; tardi", forms:{pres_aff:"おそいです", pres_neg:"おそくないです", past_aff:"おそかったです", past_neg:"おそくなかったです", te:"おそくて"}},
  {jp:"ねむい", kanji:"眠い", type:"i", it:"assonnato", forms:{pres_aff:"ねむいです", pres_neg:"ねむくないです", past_aff:"ねむかったです", past_neg:"ねむくなかったです", te:"ねむくて"}},
  {jp:"かんたん", kanji:"簡単", type:"na", it:"semplice", forms:{pres_aff:"かんたんです", pres_neg:"かんたんじゃないです", past_aff:"かんたんでした", past_neg:"かんたんじゃなかったです", te:"かんたんで"}}
];