// Database vocabolario Genki I - Lezioni 1-10
// Ogni voce: {jp, kanji, ro, it}

const VOCAB = {
  lezione1: [
    {jp:"だいがく", kanji:"大学", ro:"daigaku", it:"università"},
    {jp:"こうこう", kanji:"高校", ro:"koukou", it:"liceo"},
    {jp:"がくせい", kanji:"学生", ro:"gakusee", it:"studente"},
    {jp:"だいがくせい", kanji:"大学生", ro:"daigakusee", it:"studente universitario"},
    {jp:"りゅうがくせい", kanji:"留学生", ro:"ryuugakusee", it:"studente straniero"},
    {jp:"せんせい", kanji:"先生", ro:"sensee", it:"insegnante / professore"},
    {jp:"いちねんせい", kanji:"一年生", ro:"ichinensee", it:"studente del primo anno"},
    {jp:"せんこう", kanji:"専攻", ro:"senkoo", it:"materia di specializzazione"},
    {jp:"わたし", kanji:"私", ro:"watashi", it:"io"},
    {jp:"ともだち", kanji:"友達", ro:"tomodachi", it:"amico/a"},
    {jp:"にほんじん", kanji:"日本人", ro:"nihonjin", it:"giapponese (persona)"},
    {jp:"いま", kanji:"今", ro:"ima", it:"adesso"},
    {jp:"ごぜん", kanji:"午前", ro:"gozen", it:"mattina (A.M.)"},
    {jp:"ごご", kanji:"午後", ro:"gogo", it:"pomeriggio (P.M.)"},
    {jp:"いちじ", kanji:"一時", ro:"ichiji", it:"l'una (in punto)"},
    {jp:"はん", kanji:"半", ro:"han", it:"mezza"},
    {jp:"にじはん", kanji:"二時半", ro:"nijihan", it:"le due e mezza"},
    {jp:"にほん", kanji:"日本", ro:"Nihon", it:"Giappone", cat:"countries"},
    {jp:"アメリカ", kanji:null, ro:"Amerika", it:"Stati Uniti", cat:"countries"},
    {jp:"にほんご", kanji:"日本語", ro:"nihongo", it:"lingua giapponese"},
    {jp:"でんわ", kanji:"電話", ro:"denwa", it:"telefono"},
    {jp:"ばんごう", kanji:"番号", ro:"bangoo", it:"numero"},
    {jp:"なまえ", kanji:"名前", ro:"namae", it:"nome"},
    {jp:"なに", kanji:"何", ro:"nani", it:"cosa"},
    {jp:"あのう", kanji:null, ro:"anoo", it:"ehm..."},
    {jp:"はい", kanji:null, ro:"hai", it:"sì"},
    {jp:"そうです", kanji:null, ro:"soo desu", it:"è così / esatto"},
    {jp:"そうですか", kanji:null, ro:"soo desu ka", it:"ah sì? / davvero?"},
    {jp:"イギリス", kanji:null, ro:"Igirisu", it:"Regno Unito", cat:"countries"},
    {jp:"オーストラリア", kanji:null, ro:"Oosutoraria", it:"Australia", cat:"countries"},
    {jp:"かんこく", kanji:"韓国", ro:"Kankoku", it:"Corea", cat:"countries"},
    {jp:"カナダ", kanji:null, ro:"Kanada", it:"Canada", cat:"countries"},
    {jp:"ちゅうごく", kanji:"中国", ro:"Chuugoku", it:"Cina", cat:"countries"},
    {jp:"インド", kanji:null, ro:"Indo", it:"India", cat:"countries"},
    {jp:"エジプト", kanji:null, ro:"Ejiputo", it:"Egitto", cat:"countries"},
    {jp:"フィリピン", kanji:null, ro:"Firipin", it:"Filippine", cat:"countries"},
    {jp:"けいざい", kanji:"経済", ro:"keezai", it:"economia"},
    {jp:"こうがく", kanji:"工学", ro:"koogaku", it:"ingegneria"},
    {jp:"こくさいかんけい", kanji:"国際関係", ro:"kokusaikankee", it:"relazioni internazionali"},
    {jp:"コンピューター", kanji:null, ro:"konpyuutaa", it:"informatica"},
    {jp:"せいじ", kanji:"政治", ro:"seiji", it:"politica"},
    {jp:"せいぶつがく", kanji:"生物学", ro:"seebutsugaku", it:"biologia"},
    {jp:"ビジネス", kanji:null, ro:"bijinesu", it:"business"},
    {jp:"ぶんがく", kanji:"文学", ro:"bungaku", it:"letteratura"},
    {jp:"れきし", kanji:"歴史", ro:"rekishi", it:"storia"},
    {jp:"いしゃ", kanji:"医者", ro:"isha", it:"medico"},
    {jp:"かいしゃいん", kanji:"会社員", ro:"kaishain", it:"impiegato/a"},
    {jp:"かんごし", kanji:"看護師", ro:"kangoshi", it:"infermiere/a"},
    {jp:"こうこうせい", kanji:"高校生", ro:"koukoosee", it:"studente liceale"},
    {jp:"しゅふ", kanji:"主婦", ro:"shufu", it:"casalinga"},
    {jp:"だいがくいんせい", kanji:"大学院生", ro:"daigakuinsee", it:"studente laureato / dottorando"},
    {jp:"べんごし", kanji:"弁護士", ro:"bengoshi", it:"avvocato"},
    {jp:"おかあさん", kanji:"お母さん", ro:"okaasan", it:"madre", cat:"family"},
    {jp:"おとうさん", kanji:"お父さん", ro:"otoosan", it:"padre", cat:"family"},
    {jp:"おねえさん", kanji:"お姉さん", ro:"oneesan", it:"sorella maggiore", cat:"family"},
    {jp:"おにいさん", kanji:"お兄さん", ro:"oniisan", it:"fratello maggiore", cat:"family"},
    {jp:"いもうと", kanji:"妹", ro:"imooto", it:"sorella minore", cat:"family"},
    {jp:"おとうと", kanji:"弟", ro:"otooto", it:"fratello minore", cat:"family"},
    {jp:"にじ", kanji:"二時", ro:null, it:"le due (in punto)"},
    {jp:"さんじ", kanji:"三時", ro:null, it:"le tre (in punto)"},
    {jp:"よじ", kanji:"四時", ro:null, it:"le quattro (in punto)"},
    {jp:"ごじ", kanji:"五時", ro:null, it:"le cinque (in punto)"},
    {jp:"ろくじ", kanji:"六時", ro:null, it:"le sei (in punto)"},
    {jp:"しちじ", kanji:"七時", ro:null, it:"le sette (in punto)"},
    {jp:"はちじ", kanji:"八時", ro:null, it:"le otto (in punto)"},
    {jp:"くじ", kanji:"九時", ro:null, it:"le nove (in punto)"},
    {jp:"じゅうじ", kanji:"十時", ro:null, it:"le dieci (in punto)"},
    {jp:"じゅういちじ", kanji:"十一時", ro:null, it:"le undici (in punto)"},
    {jp:"じゅうにじ", kanji:"十二時", ro:null, it:"le dodici (in punto)"},
    {jp:"いっぷん", kanji:"一分", ro:null, it:"un minuto"},
    {jp:"にふん", kanji:"二分", ro:null, it:"due minuti"},
    {jp:"さんぷん", kanji:"三分", ro:null, it:"tre minuti"},
    {jp:"よんぷん", kanji:"四分", ro:null, it:"quattro minuti"},
    {jp:"ごふん", kanji:"五分", ro:null, it:"cinque minuti"},
    {jp:"じゅっぷん", kanji:"十分", ro:null, it:"dieci minuti"},
    {jp:"じゅうごふん", kanji:"十五分", ro:null, it:"quindici minuti"},
    {jp:"にじゅっぷん", kanji:"二十分", ro:null, it:"venti minuti"},
    {jp:"さんじゅっぷん", kanji:"三十分", ro:null, it:"trenta minuti"}
  ],
  lezione2: [
    {jp:"これ", kanji:null, ro:"kore", it:"questo (qui)"},
    {jp:"それ", kanji:null, ro:"sore", it:"quello (lì)"},
    {jp:"あれ", kanji:null, ro:"are", it:"quello (là, lontano)"},
    {jp:"どれ", kanji:null, ro:"dore", it:"quale"},
    {jp:"この", kanji:null, ro:"kono", it:"questo... (+nome)"},
    {jp:"その", kanji:null, ro:"sono", it:"quel... (+nome)"},
    {jp:"あの", kanji:null, ro:"ano", it:"quel... (+nome, lontano)"},
    {jp:"どの", kanji:null, ro:"dono", it:"quale... (+nome)"},
    {jp:"ここ", kanji:null, ro:"koko", it:"qui"},
    {jp:"そこ", kanji:null, ro:"soko", it:"lì"},
    {jp:"あそこ", kanji:null, ro:"asoko", it:"là (lontano)"},
    {jp:"どこ", kanji:null, ro:"doko", it:"dove"},
    {jp:"だれ", kanji:null, ro:"dare", it:"chi"},
    {jp:"おいしい", kanji:null, ro:"oishii", it:"delizioso"},
    {jp:"さかな", kanji:null, ro:"sakana", it:"pesce"},
    {jp:"とんかつ", kanji:null, ro:"tonkatsu", it:"cotoletta di maiale"},
    {jp:"にく", kanji:null, ro:"niku", it:"carne"},
    {jp:"メニュー", kanji:null, ro:"menyuu", it:"menù"},
    {jp:"やさい", kanji:null, ro:"yasai", it:"verdura"},
    {jp:"かさ", kanji:null, ro:"kasa", it:"ombrello"},
    {jp:"かばん", kanji:null, ro:"kaban", it:"borsa"},
    {jp:"くつ", kanji:null, ro:"kutsu", it:"scarpe"},
    {jp:"さいふ", kanji:null, ro:"saifu", it:"portafoglio"},
    {jp:"ジーンズ", kanji:null, ro:"jiinzu", it:"jeans"},
    {jp:"じてんしゃ", kanji:null, ro:"jitensha", it:"bicicletta"},
    {jp:"しんぶん", kanji:null, ro:"shinbun", it:"giornale"},
    {jp:"スマホ", kanji:null, ro:"sumaho", it:"smartphone"},
    {jp:"Tシャツ", kanji:null, ro:"tiishatsu", it:"maglietta"},
    {jp:"とけい", kanji:null, ro:"tokee", it:"orologio"},
    {jp:"ノート", kanji:null, ro:"nooto", it:"quaderno"},
    {jp:"ペン", kanji:null, ro:"pen", it:"penna"},
    {jp:"ぼうし", kanji:null, ro:"booshi", it:"cappello"},
    {jp:"ほん", kanji:null, ro:"hon", it:"libro"},
    {jp:"ぎんこう", kanji:null, ro:"ginkoo", it:"banca"},
    {jp:"コンビニ", kanji:null, ro:"konbini", it:"minimarket"},
    {jp:"トイレ", kanji:null, ro:"toire", it:"bagno"},
    {jp:"としょかん", kanji:null, ro:"toshokan", it:"biblioteca"},
    {jp:"ゆうびんきょく", kanji:null, ro:"yuubinkyoku", it:"ufficio postale"},
    {jp:"イギリス", kanji:null, ro:"Igirisu", it:"Regno Unito", cat:"countries"},
    {jp:"かんこく", kanji:null, ro:"Kankoku", it:"Corea", cat:"countries"},
    {jp:"ちゅうごく", kanji:null, ro:"Chuugoku", it:"Cina", cat:"countries"},
    {jp:"えいご", kanji:null, ro:"eego", it:"lingua inglese"},
    {jp:"けいざい", kanji:null, ro:"keezai", it:"economia"},
    {jp:"コンピューター", kanji:null, ro:"konpyuutaa", it:"informatica"},
    {jp:"ビジネス", kanji:null, ro:"bijinesu", it:"business"},
    {jp:"れきし", kanji:null, ro:"rekishi", it:"storia"},
    {jp:"おかあさん", kanji:null, ro:"okaasan", it:"madre", cat:"family"},
    {jp:"おとうさん", kanji:null, ro:"otoosan", it:"padre", cat:"family"},
    {jp:"いくら", kanji:null, ro:"ikura", it:"quanto costa"},
    {jp:"〜えん", kanji:null, ro:"en", it:"...yen"},
    {jp:"たかい", kanji:null, ro:"takai", it:"costoso"},
    {jp:"いらっしゃいませ", kanji:null, ro:"irasshaimase", it:"Benvenuto (nel negozio)"},
    {jp:"（〜を）おねがいします", kanji:null, ro:"onegaishimasu", it:"..., per favore"},
    {jp:"（〜を）ください", kanji:null, ro:"kudasai", it:"Mi dia... per favore"},
    {jp:"じゃあ", kanji:null, ro:"jaa", it:"allora; in tal caso"},
    {jp:"どうぞ", kanji:null, ro:"doozo", it:"prego; ecco a lei"},
    {jp:"どうも", kanji:null, ro:"doomo", it:"grazie"},
    {jp:"こくばん", kanji:"黒板", ro:null, it:"lavagna"},
    {jp:"カーテン", kanji:null, ro:null, it:"tenda"},
    {jp:"ドア", kanji:null, ro:null, it:"porta"},
    {jp:"じしょ", kanji:"辞書", ro:null, it:"dizionario"},
    {jp:"けしゴム", kanji:"消しゴム", ro:null, it:"gomma da cancellare"},
    {jp:"えんぴつ", kanji:"鉛筆", ro:null, it:"matita"},
    {jp:"わかりましたか", kanji:null, ro:null, it:"hai capito?"},
    {jp:"わかりました", kanji:null, ro:null, it:"ho capito"},
    {jp:"わかりません", kanji:null, ro:null, it:"non capisco/non lo so"}
  ],
  lezione3: [
    {jp:"えいが", kanji:"映画", ro:null, it:"film"},
    {jp:"おんがく", kanji:"音楽", ro:null, it:"musica"},
    {jp:"ざっし", kanji:"雑誌", ro:null, it:"rivista"},
    {jp:"スポーツ", kanji:null, ro:null, it:"sport"},
    {jp:"デート", kanji:null, ro:null, it:"appuntamento romantico"},
    {jp:"テニス", kanji:null, ro:null, it:"tennis"},
    {jp:"テレビ", kanji:null, ro:null, it:"TV"},
    {jp:"アイスクリーム", kanji:null, ro:null, it:"gelato"},
    {jp:"ハンバーガー", kanji:null, ro:null, it:"hamburger"},
    {jp:"おさけ", kanji:"お酒", ro:null, it:"sakè; alcolico"},
    {jp:"おちゃ", kanji:"お茶", ro:null, it:"tè verde"},
    {jp:"コーヒー", kanji:null, ro:null, it:"caffè"},
    {jp:"みず", kanji:"水", ro:null, it:"acqua"},
    {jp:"あさごはん", kanji:"朝ご飯", ro:null, it:"colazione"},
    {jp:"ひるごはん", kanji:"昼ご飯", ro:null, it:"pranzo"},
    {jp:"ばんごはん", kanji:"晩ご飯", ro:null, it:"cena"},
    {jp:"いえ", kanji:"家", ro:null, it:"casa"},
    {jp:"うち", kanji:null, ro:null, it:"casa (propria)"},
    {jp:"がっこう", kanji:"学校", ro:null, it:"scuola"},
    {jp:"カフェ", kanji:null, ro:null, it:"caffetteria"},
    {jp:"あした", kanji:"明日", ro:null, it:"domani"},
    {jp:"きょう", kanji:"今日", ro:null, it:"oggi"},
    {jp:"あさ", kanji:"朝", ro:null, it:"mattina"},
    {jp:"こんばん", kanji:"今晩", ro:null, it:"stasera"},
    {jp:"まいにち", kanji:"毎日", ro:null, it:"ogni giorno"},
    {jp:"まいばん", kanji:"毎晩", ro:null, it:"ogni sera"},
    {jp:"しゅうまつ", kanji:"週末", ro:null, it:"weekend"},
    {jp:"どようび", kanji:"土曜日", ro:null, it:"sabato", cat:"days_of_week"},
    {jp:"にちようび", kanji:"日曜日", ro:null, it:"domenica", cat:"days_of_week"},
    {jp:"いつ", kanji:null, ro:null, it:"quando"},
    {jp:"〜ごろ", kanji:null, ro:null, it:"circa (tempo)"},
    {jp:"いく", kanji:"行く", ro:null, it:"andare"},
    {jp:"かえる", kanji:"帰る", ro:null, it:"tornare"},
    {jp:"きく", kanji:"聞く", ro:null, it:"ascoltare"},
    {jp:"のむ", kanji:"飲む", ro:null, it:"bere"},
    {jp:"はなす", kanji:"話す", ro:null, it:"parlare"},
    {jp:"よむ", kanji:"読む", ro:null, it:"leggere"},
    {jp:"おきる", kanji:"起きる", ro:null, it:"alzarsi"},
    {jp:"たべる", kanji:"食べる", ro:null, it:"mangiare"},
    {jp:"ねる", kanji:"寝る", ro:null, it:"dormire; andare a letto"},
    {jp:"みる", kanji:"見る", ro:null, it:"vedere; guardare"},
    {jp:"くる", kanji:"来る", ro:null, it:"venire"},
    {jp:"する", kanji:null, ro:null, it:"fare"},
    {jp:"べんきょうする", kanji:"勉強する", ro:null, it:"studiare"},
    {jp:"いい", kanji:null, ro:null, it:"buono"},
    {jp:"はやい", kanji:"早い", ro:null, it:"presto"},
    {jp:"あまり＋negativo", kanji:null, ro:null, it:"non molto"},
    {jp:"ぜんぜん＋negativo", kanji:"全然", ro:null, it:"per niente"},
    {jp:"たいてい", kanji:null, ro:null, it:"di solito"},
    {jp:"ちょっと", kanji:null, ro:null, it:"un po'"},
    {jp:"ときどき", kanji:"時々", ro:null, it:"a volte"},
    {jp:"よく", kanji:null, ro:null, it:"spesso; molto"},
    {jp:"そうですね", kanji:null, ro:null, it:"vediamo; è così"},
    {jp:"でも", kanji:null, ro:null, it:"ma"},
    {jp:"どうですか", kanji:null, ro:null, it:"che ne dici di...?"},
    {jp:"ええ", kanji:null, ro:null, it:"sì"}
  ],
  lezione4: [
    {jp:"ゲーム", kanji:null, ro:null, it:"gioco"},
    {jp:"アルバイト", kanji:null, ro:null, it:"lavoretto part-time"},
    {jp:"かいもの", kanji:"買い物", ro:null, it:"spesa"},
    {jp:"クラス", kanji:null, ro:null, it:"lezione (classe)"},
    {jp:"いぬ", kanji:"犬", ro:null, it:"cane"},
    {jp:"ねこ", kanji:"猫", ro:null, it:"gatto"},
    {jp:"ひと", kanji:"人", ro:null, it:"persona"},
    {jp:"こども", kanji:"子供", ro:null, it:"bambino"},
    {jp:"あなた", kanji:null, ro:null, it:"tu"},
    {jp:"いす", kanji:null, ro:null, it:"sedia"},
    {jp:"つくえ", kanji:"机", ro:null, it:"scrivania"},
    {jp:"しゃしん", kanji:"写真", ro:null, it:"foto"},
    {jp:"はな", kanji:"花", ro:null, it:"fiore"},
    {jp:"レポート", kanji:null, ro:null, it:"relazione (scolastica)"},
    {jp:"ごはん", kanji:"ご飯", ro:null, it:"riso; pasto"},
    {jp:"パン", kanji:null, ro:null, it:"pane"},
    {jp:"おてら", kanji:"お寺", ro:null, it:"tempio"},
    {jp:"こうえん", kanji:"公園", ro:null, it:"parco"},
    {jp:"スーパー", kanji:null, ro:null, it:"supermercato"},
    {jp:"バスてい", kanji:"バス停", ro:null, it:"fermata bus"},
    {jp:"びょういん", kanji:"病院", ro:null, it:"ospedale"},
    {jp:"ホテル", kanji:null, ro:null, it:"hotel"},
    {jp:"ほんや", kanji:"本屋", ro:null, it:"libreria"},
    {jp:"まち", kanji:"町", ro:null, it:"città"},
    {jp:"レストラン", kanji:null, ro:null, it:"ristorante"},
    {jp:"きのう", kanji:"昨日", ro:null, it:"ieri"},
    {jp:"〜じかん", kanji:"〜時間", ro:null, it:"...ore"},
    {jp:"いちじかん", kanji:"一時間", ro:null, it:"un'ora"},
    {jp:"せんしゅう", kanji:"先週", ro:null, it:"settimana scorsa"},
    {jp:"とき", kanji:"時", ro:null, it:"quando..."},
    {jp:"げつようび", kanji:"月曜日", ro:null, it:"lunedì", cat:"days_of_week"},
    {jp:"かようび", kanji:"火曜日", ro:null, it:"martedì", cat:"days_of_week"},
    {jp:"すいようび", kanji:"水曜日", ro:null, it:"mercoledì", cat:"days_of_week"},
    {jp:"もくようび", kanji:"木曜日", ro:null, it:"giovedì", cat:"days_of_week"},
    {jp:"きんようび", kanji:"金曜日", ro:null, it:"venerdì", cat:"days_of_week"},
    {jp:"あう", kanji:"会う", ro:null, it:"incontrare"},
    {jp:"ある", kanji:null, ro:null, it:"esserci (cose)"},
    {jp:"かう", kanji:"買う", ro:null, it:"comprare"},
    {jp:"かく", kanji:"書く", ro:null, it:"scrivere"},
    {jp:"とる", kanji:"撮る", ro:null, it:"scattare (foto)"},
    {jp:"まつ", kanji:"待つ", ro:null, it:"aspettare"},
    {jp:"わかる", kanji:null, ro:null, it:"capire"},
    {jp:"いる", kanji:"居る", ro:null, it:"esserci (persone/animali)"},
    {jp:"〜ぐらい", kanji:null, ro:null, it:"circa"},
    {jp:"ごめんなさい", kanji:null, ro:null, it:"mi dispiace"},
    {jp:"それから", kanji:null, ro:null, it:"e poi"},
    {jp:"だから", kanji:null, ro:null, it:"quindi; perciò"},
    {jp:"たくさん", kanji:null, ro:null, it:"molti"},
    {jp:"〜と", kanji:null, ro:null, it:"insieme a; e"},
    {jp:"どうして", kanji:null, ro:null, it:"perché"},
    {jp:"ひとりで", kanji:"一人で", ro:null, it:"da solo"},
    {jp:"もしもし", kanji:null, ro:null, it:"pronto? (al telefono)"}
  ],
  lezione5: [
    {jp:"たべもの", kanji:"食べ物", ro:null, it:"cibo"},
    {jp:"のみもの", kanji:"飲み物", ro:null, it:"bevanda"},
    {jp:"くだもの", kanji:"果物", ro:null, it:"frutta"},
    {jp:"やすみ", kanji:"休み", ro:null, it:"vacanza; giorno libero"},
    {jp:"りょこう", kanji:"旅行", ro:null, it:"viaggio"},
    {jp:"うみ", kanji:"海", ro:null, it:"mare"},
    {jp:"サーフィン", kanji:null, ro:null, it:"surf"},
    {jp:"おみやげ", kanji:"お土産", ro:null, it:"souvenir"},
    {jp:"バス", kanji:null, ro:null, it:"autobus"},
    {jp:"てんき", kanji:"天気", ro:null, it:"tempo (meteo)"},
    {jp:"しゅくだい", kanji:"宿題", ro:null, it:"compiti"},
    {jp:"テスト", kanji:null, ro:null, it:"test"},
    {jp:"たんじょうび", kanji:"誕生日", ro:null, it:"compleanno"},
    {jp:"へや", kanji:"部屋", ro:null, it:"stanza"},
    {jp:"ぼく", kanji:"僕", ro:null, it:"io (usato dagli uomini)"},
    {jp:"Lサイズ", kanji:null, ro:null, it:"taglia L"},
    {jp:"あたらしい", kanji:"新しい", ro:null, it:"nuovo"},
    {jp:"ふるい", kanji:"古い", ro:null, it:"vecchio (cose)"},
    {jp:"あつい", kanji:"暑い", ro:null, it:"caldo (tempo)"},
    {jp:"さむい", kanji:"寒い", ro:null, it:"freddo (tempo)"},
    {jp:"あつい", kanji:"熱い", ro:null, it:"caldo (cose)"},
    {jp:"いそがしい", kanji:"忙しい", ro:null, it:"impegnato"},
    {jp:"おおきい", kanji:"大きい", ro:null, it:"grande"},
    {jp:"ちいさい", kanji:"小さい", ro:null, it:"piccolo"},
    {jp:"おもしろい", kanji:"面白い", ro:null, it:"interessante; divertente"},
    {jp:"つまらない", kanji:null, ro:null, it:"noioso"},
    {jp:"やさしい", kanji:null, ro:null, it:"facile; gentile"},
    {jp:"むずかしい", kanji:"難しい", ro:null, it:"difficile"},
    {jp:"かっこいい", kanji:null, ro:null, it:"bello (aspetto)"},
    {jp:"こわい", kanji:"怖い", ro:null, it:"spaventoso"},
    {jp:"たのしい", kanji:"楽しい", ro:null, it:"divertente"},
    {jp:"やすい", kanji:"安い", ro:null, it:"economico"},
    {jp:"すき（な）", kanji:"好き", ro:null, it:"piacere (amare)"},
    {jp:"きらい（な）", kanji:"嫌い", ro:null, it:"non piacere"},
    {jp:"だいすき（な）", kanji:"大好き", ro:null, it:"amare molto"},
    {jp:"だいきらい（な）", kanji:"大嫌い", ro:null, it:"odiare"},
    {jp:"きれい（な）", kanji:null, ro:null, it:"bello; pulito"},
    {jp:"げんき（な）", kanji:"元気", ro:null, it:"in salute; energico"},
    {jp:"しずか（な）", kanji:"静か", ro:null, it:"silenzioso"},
    {jp:"にぎやか（な）", kanji:null, ro:null, it:"vivace"},
    {jp:"ひま（な）", kanji:"暇", ro:null, it:"libero (tempo)"},
    {jp:"およぐ", kanji:"泳ぐ", ro:null, it:"nuotare"},
    {jp:"きく", kanji:"聞く", ro:null, it:"chiedere"},
    {jp:"のる", kanji:"乗る", ro:null, it:"salire su (mezzo)"},
    {jp:"やる", kanji:null, ro:null, it:"fare"},
    {jp:"でかける", kanji:"出かける", ro:null, it:"uscire"},
    {jp:"いっしょに", kanji:"一緒に", ro:null, it:"insieme"},
    {jp:"すごく", kanji:null, ro:null, it:"estremamente"},
    {jp:"だいじょうぶ", kanji:"大丈夫", ro:null, it:"va bene; tutto ok"},
    {jp:"とても", kanji:null, ro:null, it:"molto"},
    {jp:"どんな", kanji:null, ro:null, it:"che tipo di"},
    {jp:"〜まい", kanji:"〜枚", ro:null, it:"contatore oggetti piatti"}
  ],
  lezione6: [
    {jp:"かんじ", kanji:"漢字", ro:null, it:"kanji"},
    {jp:"きょうかしょ", kanji:"教科書", ro:null, it:"libro di testo"},
    {jp:"ページ", kanji:null, ro:null, it:"pagina"},
    {jp:"つぎ", kanji:"次", ro:null, it:"prossimo"},
    {jp:"おかね", kanji:"お金", ro:null, it:"soldi"},
    {jp:"にもつ", kanji:"荷物", ro:null, it:"bagaglio"},
    {jp:"パソコン", kanji:null, ro:null, it:"computer"},
    {jp:"シャワー", kanji:null, ro:null, it:"doccia"},
    {jp:"エアコン", kanji:null, ro:null, it:"condizionatore"},
    {jp:"でんき", kanji:"電気", ro:null, it:"elettricità"},
    {jp:"まど", kanji:"窓", ro:null, it:"finestra"},
    {jp:"でんしゃ", kanji:"電車", ro:null, it:"treno"},
    {jp:"くに", kanji:"国", ro:null, it:"paese"},
    {jp:"こんしゅう", kanji:"今週", ro:null, it:"questa settimana"},
    {jp:"らいしゅう", kanji:"来週", ro:null, it:"prossima settimana"},
    {jp:"らいねん", kanji:"来年", ro:null, it:"prossimo anno"},
    {jp:"よる", kanji:"夜", ro:null, it:"notte"},
    {jp:"たいへん（な）", kanji:"大変", ro:null, it:"difficile; faticoso"},
    {jp:"あそぶ", kanji:"遊ぶ", ro:null, it:"giocare"},
    {jp:"いそぐ", kanji:"急ぐ", ro:null, it:"affrettarsi"},
    {jp:"かえす", kanji:"返す", ro:null, it:"restituire"},
    {jp:"けす", kanji:"消す", ro:null, it:"spegnere; cancellare"},
    {jp:"しぬ", kanji:"死ぬ", ro:null, it:"morire"},
    {jp:"すわる", kanji:"座る", ro:null, it:"sedersi"},
    {jp:"たつ", kanji:"立つ", ro:null, it:"alzarsi in piedi"},
    {jp:"たばこをすう", kanji:"たばこを吸う", ro:null, it:"fumare"},
    {jp:"つかう", kanji:"使う", ro:null, it:"usare"},
    {jp:"てつだう", kanji:"手伝う", ro:null, it:"aiutare"},
    {jp:"はいる", kanji:"入る", ro:null, it:"entrare"},
    {jp:"もつ", kanji:"持つ", ro:null, it:"portare; tenere"},
    {jp:"やすむ", kanji:"休む", ro:null, it:"riposare; assentarsi"},
    {jp:"あける", kanji:"開ける", ro:null, it:"aprire"},
    {jp:"しめる", kanji:"閉める", ro:null, it:"chiudere"},
    {jp:"おしえる", kanji:"教える", ro:null, it:"insegnare"},
    {jp:"わすれる", kanji:"忘れる", ro:null, it:"dimenticare"},
    {jp:"おりる", kanji:"降りる", ro:null, it:"scendere"},
    {jp:"かりる", kanji:"借りる", ro:null, it:"prendere in prestito"},
    {jp:"シャワーをあびる", kanji:null, ro:null, it:"fare la doccia"},
    {jp:"つける", kanji:null, ro:null, it:"accendere"},
    {jp:"でんわする", kanji:"電話する", ro:null, it:"telefonare"},
    {jp:"つれてくる", kanji:"連れてくる", ro:null, it:"portare (una persona)"},
    {jp:"もってくる", kanji:"持ってくる", ro:null, it:"portare (una cosa)"},
    {jp:"あとで", kanji:"後で", ro:null, it:"più tardi"},
    {jp:"すぐ", kanji:null, ro:null, it:"subito"},
    {jp:"ゆっくり", kanji:null, ro:null, it:"lentamente"},
    {jp:"けっこうです", kanji:"結構です", ro:null, it:"va bene così; non serve"},
    {jp:"ほんとうですか", kanji:"本当ですか", ro:null, it:"davvero?"},
    {jp:"みちをわたる", kanji:"道を渡る", ro:null, it:"attraversare la strada"},
    {jp:"ひだりにまがる", kanji:"左に曲がる", ro:null, it:"girare a sinistra"},
    {jp:"みぎにまがる", kanji:"右に曲がる", ro:null, it:"girare a destra"},
    {jp:"まっすぐいく", kanji:"まっすぐ行く", ro:null, it:"andare dritto"},
    {jp:"かど", kanji:"角", ro:null, it:"angolo (della strada)"},
    {jp:"しんごう", kanji:"信号", ro:null, it:"semaforo"},
    {jp:"きた", kanji:"北", ro:null, it:"nord"},
    {jp:"にし", kanji:"西", ro:null, it:"ovest"},
    {jp:"ひがし", kanji:"東", ro:null, it:"est"},
    {jp:"みなみ", kanji:"南", ro:null, it:"sud"}
  ],
  lezione7: [
    {jp:"かぞく", kanji:"家族", ro:null, it:"famiglia", cat:"family"},
    {jp:"おじいさん", kanji:null, ro:null, it:"nonno"},
    {jp:"おばあさん", kanji:null, ro:null, it:"nonna"},
    {jp:"おにいさん", kanji:"お兄さん", ro:null, it:"fratello maggiore", cat:"family"},
    {jp:"おねえさん", kanji:"お姉さん", ro:null, it:"sorella maggiore", cat:"family"},
    {jp:"ちち", kanji:"父", ro:null, it:"padre (mio)", cat:"family"},
    {jp:"はは", kanji:"母", ro:null, it:"madre (mia)", cat:"family"},
    {jp:"あに", kanji:"兄", ro:null, it:"fratello maggiore (mio)", cat:"family"},
    {jp:"あね", kanji:"姉", ro:null, it:"sorella maggiore (mia)", cat:"family"},
    {jp:"いもうと", kanji:"妹", ro:null, it:"sorella minore", cat:"family"},
    {jp:"おとうと", kanji:"弟", ro:null, it:"fratello minore", cat:"family"},
    {jp:"きょうだい", kanji:"兄弟", ro:null, it:"fratelli", cat:"family"},
    {jp:"おとこのひと", kanji:"男の人", ro:null, it:"uomo"},
    {jp:"おんなのひと", kanji:"女の人", ro:null, it:"donna"},
    {jp:"かいしゃ", kanji:"会社", ro:null, it:"azienda"},
    {jp:"しょくどう", kanji:"食堂", ro:null, it:"mensa"},
    {jp:"デパート", kanji:null, ro:null, it:"grande magazzino"},
    {jp:"かみ", kanji:"髪", ro:null, it:"capelli"},
    {jp:"くち", kanji:"口", ro:null, it:"bocca"},
    {jp:"め", kanji:"目", ro:null, it:"occhio"},
    {jp:"めがね", kanji:"眼鏡", ro:null, it:"occhiali"},
    {jp:"うた", kanji:"歌", ro:null, it:"canzone"},
    {jp:"サークル", kanji:null, ro:null, it:"club; circolo"},
    {jp:"くるま", kanji:"車", ro:null, it:"macchina"},
    {jp:"ながい", kanji:"長い", ro:null, it:"lungo"},
    {jp:"みじかい", kanji:"短い", ro:null, it:"corto"},
    {jp:"はやい", kanji:"速い", ro:null, it:"veloce"},
    {jp:"せがたかい", kanji:"背が高い", ro:null, it:"alto (statura)"},
    {jp:"せがひくい", kanji:"背が低い", ro:null, it:"basso (statura)"},
    {jp:"あたまがいい", kanji:"頭がいい", ro:null, it:"intelligente"},
    {jp:"かわいい", kanji:null, ro:null, it:"carino"},
    {jp:"しんせつ（な）", kanji:"親切", ro:null, it:"gentile"},
    {jp:"べんり（な）", kanji:"便利", ro:null, it:"comodo"},
    {jp:"うたう", kanji:"歌う", ro:null, it:"cantare"},
    {jp:"かぶる", kanji:null, ro:null, it:"indossare (cappello)"},
    {jp:"はく", kanji:null, ro:null, it:"indossare (sotto la vita)"},
    {jp:"しる", kanji:"知る", ro:null, it:"conoscere; sapere"},
    {jp:"すむ", kanji:"住む", ro:null, it:"vivere; abitare"},
    {jp:"はたらく", kanji:"働く", ro:null, it:"lavorare"},
    {jp:"ふとる", kanji:"太る", ro:null, it:"ingrassare"},
    {jp:"（めがねを）かける", kanji:null, ro:null, it:"indossare (occhiali)"},
    {jp:"きる", kanji:"着る", ro:null, it:"indossare (sopra la vita)"},
    {jp:"やせる", kanji:null, ro:null, it:"dimagrire"},
    {jp:"けっこんする", kanji:"結婚する", ro:null, it:"sposarsi"},
    {jp:"〜が", kanji:null, ro:null, it:"...ma"},
    {jp:"なにも＋negativo", kanji:"何も", ro:null, it:"niente"},
    {jp:"〜にん", kanji:"〜人", ro:null, it:"contatore persone"},
    {jp:"ひとり", kanji:"一人", ro:null, it:"una persona"},
    {jp:"ふたり", kanji:"二人", ro:null, it:"due persone"},
    {jp:"べつに＋negativo", kanji:"別に", ro:null, it:"niente in particolare"},
    {jp:"もちろん", kanji:null, ro:null, it:"certamente"},
    {jp:"よかったら", kanji:null, ro:null, it:"se ti va"},
    {jp:"まゆげ", kanji:"眉毛", ro:null, it:"sopracciglio"},
    {jp:"みみ", kanji:"耳", ro:null, it:"orecchio"},
    {jp:"はな", kanji:"鼻", ro:null, it:"naso"},
    {jp:"ゆび", kanji:"指", ro:null, it:"dito"},
    {jp:"て", kanji:"手", ro:null, it:"mano"},
    {jp:"くび", kanji:"首", ro:null, it:"collo"},
    {jp:"あたま", kanji:"頭", ro:null, it:"testa"},
    {jp:"かた", kanji:"肩", ro:null, it:"spalla"},
    {jp:"むね", kanji:"胸", ro:null, it:"petto"},
    {jp:"せなか", kanji:"背中", ro:null, it:"schiena"},
    {jp:"おしり", kanji:null, ro:null, it:"sedere"}
  ],
  lezione8: [
    {jp:"はれ", kanji:"晴れ", ro:null, it:"sereno"},
    {jp:"あめ", kanji:"雨", ro:null, it:"pioggia"},
    {jp:"くもり", kanji:"曇り", ro:null, it:"nuvoloso"},
    {jp:"ゆき", kanji:"雪", ro:null, it:"neve"},
    {jp:"てんきよほう", kanji:"天気予報", ro:null, it:"previsioni meteo"},
    {jp:"きおん", kanji:"気温", ro:null, it:"temperatura"},
    {jp:"なつ", kanji:"夏", ro:null, it:"estate"},
    {jp:"ふゆ", kanji:"冬", ro:null, it:"inverno"},
    {jp:"けさ", kanji:"今朝", ro:null, it:"stamattina"},
    {jp:"あさって", kanji:null, ro:null, it:"dopodomani"},
    {jp:"まいしゅう", kanji:"毎週", ro:null, it:"ogni settimana"},
    {jp:"こんげつ", kanji:"今月", ro:null, it:"questo mese"},
    {jp:"らいげつ", kanji:"来月", ro:null, it:"prossimo mese"},
    {jp:"かいしゃいん", kanji:"会社員", ro:null, it:"impiegato"},
    {jp:"しごと", kanji:"仕事", ro:null, it:"lavoro"},
    {jp:"カメラ", kanji:null, ro:null, it:"macchina fotografica"},
    {jp:"カラオケ", kanji:null, ro:null, it:"karaoke"},
    {jp:"ところ", kanji:"所", ro:null, it:"luogo"},
    {jp:"トマト", kanji:null, ro:null, it:"pomodoro"},
    {jp:"はし", kanji:null, ro:null, it:"bacchette"},
    {jp:"パーティー", kanji:null, ro:null, it:"festa"},
    {jp:"バーベキュー", kanji:null, ro:null, it:"barbecue"},
    {jp:"ホームステイ", kanji:null, ro:null, it:"soggiorno in famiglia"},
    {jp:"おふろ", kanji:"お風呂", ro:null, it:"bagno (vasca)"},
    {jp:"スペイン", kanji:null, ro:null, it:"Spagna", cat:"countries"},
    {jp:"なにか", kanji:"何か", ro:null, it:"qualcosa"},
    {jp:"じょうず（な）", kanji:"上手", ro:null, it:"bravo"},
    {jp:"へた（な）", kanji:"下手", ro:null, it:"scarso"},
    {jp:"ゆうめい（な）", kanji:"有名", ro:null, it:"famoso"},
    {jp:"あらう", kanji:"洗う", ro:null, it:"lavare"},
    {jp:"いう", kanji:"言う", ro:null, it:"dire"},
    {jp:"いる", kanji:"要る", ro:null, it:"avere bisogno"},
    {jp:"おそくなる", kanji:"遅くなる", ro:null, it:"fare tardi"},
    {jp:"おふろにはいる", kanji:"お風呂に入る", ro:null, it:"fare il bagno"},
    {jp:"おもう", kanji:"思う", ro:null, it:"pensare"},
    {jp:"きる", kanji:"切る", ro:null, it:"tagliare"},
    {jp:"つくる", kanji:"作る", ro:null, it:"fare/produrre; creare"},
    {jp:"（あめ/ゆきが）ふる", kanji:"（雨/雪が）降る", ro:null, it:"piovere/nevicare"},
    {jp:"もっていく", kanji:"持っていく", ro:null, it:"portare (una cosa)"},
    {jp:"すてる", kanji:"捨てる", ro:null, it:"buttare via"},
    {jp:"はじめる", kanji:"始める", ro:null, it:"iniziare"},
    {jp:"うんてんする", kanji:"運転する", ro:null, it:"guidare"},
    {jp:"せんたくする", kanji:"洗濯する", ro:null, it:"fare il bucato"},
    {jp:"そうじする", kanji:"掃除する", ro:null, it:"pulire"},
    {jp:"りょうりする", kanji:"料理する", ro:null, it:"cucinare"},
    {jp:"うん", kanji:null, ro:null, it:"sì (informale)"},
    {jp:"ううん", kanji:null, ro:null, it:"no (informale)"},
    {jp:"いつも", kanji:null, ro:null, it:"sempre"},
    {jp:"おそく", kanji:"遅く", ro:null, it:"tardi"},
    {jp:"かんぱい", kanji:"乾杯", ro:null, it:"Cin cin!"},
    {jp:"みんなで", kanji:null, ro:null, it:"tutti insieme"},
    {jp:"ざんねん（ですね）", kanji:"残念（ですね）", ro:null, it:"che peccato"},
    {jp:"まだ＋negativo", kanji:null, ro:null, it:"non ancora"},
    {jp:"〜について", kanji:null, ro:null, it:"riguardo a..."},
    {jp:"〜ど", kanji:"〜度", ro:null, it:"...gradi"},
    {jp:"どう", kanji:null, ro:null, it:"come"},
    {jp:"いちご", kanji:null, ro:null, it:"fragola"},
    {jp:"すいか", kanji:null, ro:null, it:"anguria"},
    {jp:"みかん", kanji:null, ro:null, it:"mandarino"},
    {jp:"もも", kanji:null, ro:null, it:"pesca (frutto)"},
    {jp:"ぶどう", kanji:null, ro:null, it:"uva"},
    {jp:"にんじん", kanji:null, ro:null, it:"carota"},
    {jp:"たまねぎ", kanji:"玉ねぎ", ro:null, it:"cipolla"},
    {jp:"じゃがいも", kanji:null, ro:null, it:"patata"},
    {jp:"なす", kanji:null, ro:null, it:"melanzana"},
    {jp:"きゅうり", kanji:null, ro:null, it:"cetriolo"},
    {jp:"キャベツ", kanji:null, ro:null, it:"cavolo"},
    {jp:"ぎゅうにく", kanji:"牛肉", ro:null, it:"carne di manzo"},
    {jp:"ぶたにく", kanji:"豚肉", ro:null, it:"carne di maiale"},
    {jp:"とりにく", kanji:"鶏肉", ro:null, it:"carne di pollo"}
  ],
  lezione9: [
    {jp:"たんご", kanji:"単語", ro:null, it:"vocabolo"},
    {jp:"さくぶん", kanji:"作文", ro:null, it:"composizione"},
    {jp:"しけん", kanji:"試験", ro:null, it:"esame"},
    {jp:"てがみ", kanji:"手紙", ro:null, it:"lettera"},
    {jp:"メール", kanji:null, ro:null, it:"email"},
    {jp:"ギター", kanji:null, ro:null, it:"chitarra"},
    {jp:"ピアノ", kanji:null, ro:null, it:"piano"},
    {jp:"コンサート", kanji:null, ro:null, it:"concerto"},
    {jp:"チケット", kanji:null, ro:null, it:"biglietto"},
    {jp:"かぶき", kanji:"歌舞伎", ro:null, it:"kabuki"},
    {jp:"スキー", kanji:null, ro:null, it:"sci"},
    {jp:"おべんとう", kanji:"お弁当", ro:null, it:"pranzo al sacco"},
    {jp:"ピザ", kanji:null, ro:null, it:"pizza"},
    {jp:"びょうき", kanji:"病気", ro:null, it:"malattia"},
    {jp:"くすり", kanji:"薬", ro:null, it:"medicina"},
    {jp:"いいこ", kanji:"いい子", ro:null, it:"bravo bambino"},
    {jp:"いろ", kanji:"色", ro:null, it:"colore"},
    {jp:"こんど", kanji:"今度", ro:null, it:"prossima volta"},
    {jp:"せんげつ", kanji:"先月", ro:null, it:"mese scorso"},
    {jp:"きょねん", kanji:"去年", ro:null, it:"anno scorso"},
    {jp:"あおい", kanji:"青い", ro:null, it:"blu", cat:"colors"},
    {jp:"あかい", kanji:"赤い", ro:null, it:"rosso", cat:"colors"},
    {jp:"くろい", kanji:"黒い", ro:null, it:"nero", cat:"colors"},
    {jp:"しろい", kanji:"白い", ro:null, it:"bianco", cat:"colors"},
    {jp:"さびしい", kanji:"寂しい", ro:null, it:"solo (triste)"},
    {jp:"わかい", kanji:"若い", ro:null, it:"giovane"},
    {jp:"いじわる（な）", kanji:"意地悪", ro:null, it:"cattivo (di carattere)"},
    {jp:"おどる", kanji:"踊る", ro:null, it:"ballare"},
    {jp:"おわる", kanji:"終わる", ro:null, it:"finire"},
    {jp:"くすりをのむ", kanji:"薬を飲む", ro:null, it:"prendere medicine"},
    {jp:"にんきがある", kanji:"人気がある", ro:null, it:"essere popolare"},
    {jp:"はじまる", kanji:"始まる", ro:null, it:"iniziare (qualcosa)"},
    {jp:"ひく", kanji:"弾く", ro:null, it:"suonare (strumento a corde/piano)"},
    {jp:"もらう", kanji:null, ro:null, it:"ricevere"},
    {jp:"おぼえる", kanji:"覚える", ro:null, it:"memorizzare"},
    {jp:"でる", kanji:"出る", ro:null, it:"uscire; partecipare"},
    {jp:"うんどうする", kanji:"運動する", ro:null, it:"fare esercizio"},
    {jp:"さんぽする", kanji:"散歩する", ro:null, it:"fare una passeggiata"},
    {jp:"そう", kanji:null, ro:null, it:"(penso) così"},
    {jp:"〜から", kanji:null, ro:null, it:"da..."},
    {jp:"〜まで", kanji:null, ro:null, it:"fino a..."},
    {jp:"ぜひ", kanji:null, ro:null, it:"assolutamente"},
    {jp:"ところで", kanji:null, ro:null, it:"a proposito"},
    {jp:"みんな", kanji:null, ro:null, it:"tutti"},
    {jp:"もう", kanji:null, ro:null, it:"già"},
    {jp:"ひとつ", kanji:"一つ", ro:null, it:"uno (contando oggetti)", cat:"counting_numbers"},
    {jp:"ふたつ", kanji:"二つ", ro:null, it:"due (contando oggetti)", cat:"counting_numbers"},
    {jp:"みっつ", kanji:"三つ", ro:null, it:"tre (contando oggetti)", cat:"counting_numbers"},
    {jp:"よっつ", kanji:"四つ", ro:null, it:"quattro (contando oggetti)", cat:"counting_numbers"},
    {jp:"いつつ", kanji:"五つ", ro:null, it:"cinque (contando oggetti)", cat:"counting_numbers"},
    {jp:"むっつ", kanji:"六つ", ro:null, it:"sei (contando oggetti)", cat:"counting_numbers"},
    {jp:"ななつ", kanji:"七つ", ro:null, it:"sette (contando oggetti)", cat:"counting_numbers"},
    {jp:"やっつ", kanji:"八つ", ro:null, it:"otto (contando oggetti)", cat:"counting_numbers"},
    {jp:"ここのつ", kanji:"九つ", ro:null, it:"nove (contando oggetti)", cat:"counting_numbers"},
    {jp:"とお", kanji:"十", ro:null, it:"dieci (contando oggetti)", cat:"counting_numbers"},
    {jp:"きいろい", kanji:"黄色い", ro:null, it:"giallo"},
    {jp:"ちゃいろい", kanji:"茶色い", ro:null, it:"marrone"},
    {jp:"みどり", kanji:"緑", ro:null, it:"verde"},
    {jp:"むらさき", kanji:"紫", ro:null, it:"viola"},
    {jp:"こんいろ", kanji:"紺色", ro:null, it:"blu navy"},
    {jp:"はいいろ", kanji:"灰色", ro:null, it:"grigio"},
    {jp:"みずいろ", kanji:"水色", ro:null, it:"azzurro chiaro"},
    {jp:"きんいろ", kanji:"金色", ro:null, it:"dorato"},
    {jp:"ぎんいろ", kanji:"銀色", ro:null, it:"argento (colore)"},
    {jp:"ピンク", kanji:null, ro:null, it:"rosa"},
    {jp:"オレンジ", kanji:null, ro:null, it:"arancione"},
    {jp:"ベージュ", kanji:null, ro:null, it:"beige"}
  ],
  lezione10: [
    {jp:"きせつ", kanji:"季節", ro:null, it:"stagione"},
    {jp:"はる", kanji:"春", ro:null, it:"primavera"},
    {jp:"あき", kanji:"秋", ro:null, it:"autunno"},
    {jp:"ぎゅうにゅう", kanji:"牛乳", ro:null, it:"latte"},
    {jp:"ケーキ", kanji:null, ro:null, it:"torta"},
    {jp:"すし", kanji:null, ro:null, it:"sushi"},
    {jp:"てんぷら", kanji:"天ぷら", ro:null, it:"tempura"},
    {jp:"りんご", kanji:null, ro:null, it:"mela"},
    {jp:"りょうり", kanji:"料理", ro:null, it:"cucina"},
    {jp:"サッカー", kanji:null, ro:null, it:"calcio"},
    {jp:"やきゅう", kanji:"野球", ro:null, it:"baseball"},
    {jp:"いしゃ", kanji:"医者", ro:null, it:"dottore"},
    {jp:"おかねもち", kanji:"お金持ち", ro:null, it:"persona ricca"},
    {jp:"ゆうめいじん", kanji:"有名人", ro:null, it:"celebrità"},
    {jp:"かお", kanji:"顔", ro:null, it:"viso"},
    {jp:"としうえ", kanji:"年上", ro:null, it:"più grande (età)"},
    {jp:"えき", kanji:"駅", ro:null, it:"stazione"},
    {jp:"しんかんせん", kanji:"新幹線", ro:null, it:"Shinkansen"},
    {jp:"ちかてつ", kanji:"地下鉄", ro:null, it:"metropolitana"},
    {jp:"ふね", kanji:"船", ro:null, it:"nave"},
    {jp:"ひこうき", kanji:"飛行機", ro:null, it:"aereo"},
    {jp:"よやく", kanji:"予約", ro:null, it:"prenotazione"},
    {jp:"ツアー", kanji:null, ro:null, it:"tour"},
    {jp:"どうぶつえん", kanji:"動物園", ro:null, it:"zoo"},
    {jp:"じかん", kanji:"時間", ro:null, it:"tempo"},
    {jp:"せかい", kanji:"世界", ro:null, it:"mondo"},
    {jp:"びよういん", kanji:"美容院", ro:null, it:"salone di bellezza"},
    {jp:"てぶくろ", kanji:"手袋", ro:null, it:"guanti"},
    {jp:"せいかつ", kanji:"生活", ro:null, it:"vita quotidiana"},
    {jp:"ことし", kanji:"今年", ro:null, it:"quest'anno"},
    {jp:"あたたかい", kanji:"暖かい", ro:null, it:"caldo (tiepido)"},
    {jp:"すずしい", kanji:"涼しい", ro:null, it:"fresco"},
    {jp:"つめたい", kanji:"冷たい", ro:null, it:"freddo (cose/persone)"},
    {jp:"おそい", kanji:"遅い", ro:null, it:"lento; tardi"},
    {jp:"ねむい", kanji:"眠い", ro:null, it:"assonnato"},
    {jp:"かんたん（な）", kanji:"簡単", ro:null, it:"semplice"},
    {jp:"かかる", kanji:null, ro:null, it:"richiedere (tempo/denaro)"},
    {jp:"とまる", kanji:"泊まる", ro:null, it:"alloggiare"},
    {jp:"なる", kanji:null, ro:null, it:"diventare"},
    {jp:"きめる", kanji:"決める", ro:null, it:"decidere"},
    {jp:"ごろごろする", kanji:null, ro:null, it:"oziare a casa"},
    {jp:"りょこうする", kanji:"旅行する", ro:null, it:"viaggiare"},
    {jp:"れんしゅうする", kanji:"練習する", ro:null, it:"esercitarsi"},
    {jp:"いちばん", kanji:"一番", ro:null, it:"il più"},
    {jp:"どっち/どちら", kanji:null, ro:null, it:"quale (dei due)"},
    {jp:"はやく", kanji:"早く/速く", ro:null, it:"presto; velocemente"},
    {jp:"あるいて", kanji:"歩いて", ro:null, it:"a piedi"},
    {jp:"〜で", kanji:null, ro:null, it:"con (mezzo/strumento)"},
    {jp:"どうやって", kanji:null, ro:null, it:"come (con che mezzo)"},
    {jp:"どのぐらい", kanji:null, ro:null, it:"quanto (tempo/quantità)"},
    {jp:"〜しゅうかん", kanji:"〜週間", ro:null, it:"per ...settimane"},
    {jp:"〜かげつ", kanji:"〜か月", ro:null, it:"per ...mesi"},
    {jp:"〜ねん", kanji:"〜年", ro:null, it:"...anni"},
    {jp:"このごろ", kanji:null, ro:null, it:"di questi tempi"},
    {jp:"〜ご", kanji:"〜後", ro:null, it:"dopo..."},
    {jp:"〜か〜", kanji:null, ro:null, it:"o"},
    {jp:"ふつう", kanji:"普通", ro:null, it:"treno locale"},
    {jp:"きゅうこう", kanji:"急行", ro:null, it:"treno espresso"},
    {jp:"とっきゅう", kanji:"特急", ro:null, it:"treno superveloce"},
    {jp:"でぐち", kanji:"出口", ro:null, it:"uscita"},
    {jp:"いりぐち", kanji:"入口", ro:null, it:"entrata"},
    {jp:"かいだん", kanji:"階段", ro:null, it:"scale"},
    {jp:"ホーム", kanji:null, ro:null, it:"binario/marciapiede"},
    {jp:"きっぷうりば", kanji:"切符売り場", ro:null, it:"biglietteria"},
    {jp:"のりかえ", kanji:"乗り換え", ro:null, it:"cambio (di treno)"}
  ],

  // Useful Expressions - Lezione 4, pag. 127: giorni del mese, mesi, espressioni temporali
  utili4: [
    {jp:"ついたち", kanji:"一日", ro:"tsuitachi", it:"il giorno 1 (del mese)", cat:"days_of_month"},
    {jp:"ふつか", kanji:"二日", ro:"futsuka", it:"il giorno 2 (del mese)", cat:"days_of_month"},
    {jp:"みっか", kanji:"三日", ro:"mikka", it:"il giorno 3 (del mese)", cat:"days_of_month"},
    {jp:"よっか", kanji:"四日", ro:"yokka", it:"il giorno 4 (del mese)", cat:"days_of_month"},
    {jp:"いつか", kanji:"五日", ro:"itsuka", it:"il giorno 5 (del mese)", cat:"days_of_month"},
    {jp:"むいか", kanji:"六日", ro:"muika", it:"il giorno 6 (del mese)", cat:"days_of_month"},
    {jp:"なのか", kanji:"七日", ro:"nanoka", it:"il giorno 7 (del mese)", cat:"days_of_month"},
    {jp:"ようか", kanji:"八日", ro:"yooka", it:"il giorno 8 (del mese)", cat:"days_of_month"},
    {jp:"ここのか", kanji:"九日", ro:"kokonoka", it:"il giorno 9 (del mese)", cat:"days_of_month"},
    {jp:"とおか", kanji:"十日", ro:"tooka", it:"il giorno 10 (del mese)", cat:"days_of_month"},
    {jp:"じゅういちにち", kanji:"十一日", ro:"juuichinichi", it:"il giorno 11 (del mese)", cat:"days_of_month"},
    {jp:"じゅうににち", kanji:"十二日", ro:"juuninichi", it:"il giorno 12 (del mese)", cat:"days_of_month"},
    {jp:"じゅうさんにち", kanji:"十三日", ro:"juusannichi", it:"il giorno 13 (del mese)", cat:"days_of_month"},
    {jp:"じゅうよっか", kanji:"十四日", ro:"juuyokka", it:"il giorno 14 (del mese)", cat:"days_of_month"},
    {jp:"じゅうごにち", kanji:"十五日", ro:"juugonichi", it:"il giorno 15 (del mese)", cat:"days_of_month"},
    {jp:"じゅうろくにち", kanji:"十六日", ro:"juurokunichi", it:"il giorno 16 (del mese)", cat:"days_of_month"},
    {jp:"じゅうしちにち", kanji:"十七日", ro:"juushichinichi", it:"il giorno 17 (del mese)", cat:"days_of_month"},
    {jp:"じゅうはちにち", kanji:"十八日", ro:"juuhachinichi", it:"il giorno 18 (del mese)", cat:"days_of_month"},
    {jp:"じゅうくにち", kanji:"十九日", ro:"juukunichi", it:"il giorno 19 (del mese)", cat:"days_of_month"},
    {jp:"はつか", kanji:"二十日", ro:"hatsuka", it:"il giorno 20 (del mese)", cat:"days_of_month"},
    {jp:"にじゅういちにち", kanji:"二十一日", ro:"nijuuichinichi", it:"il giorno 21 (del mese)", cat:"days_of_month"},
    {jp:"にじゅうににち", kanji:"二十二日", ro:"nijuuninichi", it:"il giorno 22 (del mese)", cat:"days_of_month"},
    {jp:"にじゅうさんにち", kanji:"二十三日", ro:"nijuusannichi", it:"il giorno 23 (del mese)", cat:"days_of_month"},
    {jp:"にじゅうよっか", kanji:"二十四日", ro:"nijuuyokka", it:"il giorno 24 (del mese)", cat:"days_of_month"},
    {jp:"にじゅうごにち", kanji:"二十五日", ro:"nijuugonichi", it:"il giorno 25 (del mese)", cat:"days_of_month"},
    {jp:"にじゅうろくにち", kanji:"二十六日", ro:"nijuurokunichi", it:"il giorno 26 (del mese)", cat:"days_of_month"},
    {jp:"にじゅうしちにち", kanji:"二十七日", ro:"nijuushichinichi", it:"il giorno 27 (del mese)", cat:"days_of_month"},
    {jp:"にじゅうはちにち", kanji:"二十八日", ro:"nijuuhachinichi", it:"il giorno 28 (del mese)", cat:"days_of_month"},
    {jp:"にじゅうくにち", kanji:"二十九日", ro:"nijuukunichi", it:"il giorno 29 (del mese)", cat:"days_of_month"},
    {jp:"さんじゅうにち", kanji:"三十日", ro:"sanjuunichi", it:"il giorno 30 (del mese)", cat:"days_of_month"},
    {jp:"さんじゅういちにち", kanji:"三十一日", ro:"sanjuuichinichi", it:"il giorno 31 (del mese)", cat:"days_of_month"},
    {jp:"いちがつ", kanji:"一月", ro:"ichigatsu", it:"gennaio", cat:"months"},
    {jp:"にがつ", kanji:"二月", ro:"nigatsu", it:"febbraio", cat:"months"},
    {jp:"さんがつ", kanji:"三月", ro:"sangatsu", it:"marzo", cat:"months"},
    {jp:"しがつ", kanji:"四月", ro:"shigatsu", it:"aprile", cat:"months"},
    {jp:"ごがつ", kanji:"五月", ro:"gogatsu", it:"maggio", cat:"months"},
    {jp:"ろくがつ", kanji:"六月", ro:"rokugatsu", it:"giugno", cat:"months"},
    {jp:"しちがつ", kanji:"七月", ro:"shichigatsu", it:"luglio", cat:"months"},
    {jp:"はちがつ", kanji:"八月", ro:"hachigatsu", it:"agosto", cat:"months"},
    {jp:"くがつ", kanji:"九月", ro:"kugatsu", it:"settembre", cat:"months"},
    {jp:"じゅうがつ", kanji:"十月", ro:"juugatsu", it:"ottobre", cat:"months"},
    {jp:"じゅういちがつ", kanji:"十一月", ro:"juuichigatsu", it:"novembre", cat:"months"},
    {jp:"じゅうにがつ", kanji:"十二月", ro:"juunigatsu", it:"dicembre", cat:"months"},
    {jp:"おととい", kanji:null, ro:"ototoi", it:"l'altro ieri"},
    {jp:"にしゅうかんまえ", kanji:"二週間前", ro:"nishuukanmae", it:"due settimane fa"},
    {jp:"にかげつまえ", kanji:"二か月前", ro:"nikagetsumae", it:"due mesi fa"},
    {jp:"おととし", kanji:null, ro:"ototoshi", it:"due anni fa (l'anno prima dello scorso)"},
    {jp:"さらいしゅう", kanji:"再来週", ro:"saraishuu", it:"tra due settimane"},
    {jp:"さらいげつ", kanji:"再来月", ro:"saraigetsu", it:"tra due mesi"},
    {jp:"さらいねん", kanji:"再来年", ro:"sarainen", it:"tra due anni"}
  ],
  lezione11: [
    {jp:"がいこく", kanji:"外国", ro:null, it:"paese straniero"},
    {jp:"オーストラリア", kanji:null, ro:null, it:"Australia"},
    {jp:"かわ", kanji:"川", ro:null, it:"fiume"},
    {jp:"おんせん", kanji:"温泉", ro:null, it:"terme; sorgente calda"},
    {jp:"つり", kanji:null, ro:null, it:"pesca"},
    {jp:"みずうみ", kanji:"湖", ro:null, it:"lago"},
    {jp:"やま", kanji:"山", ro:null, it:"montagna"},
    {jp:"キャンプ", kanji:null, ro:null, it:"campeggio"},
    {jp:"ドライブ", kanji:null, ro:null, it:"giro in macchina"},
    {jp:"じんじゃ", kanji:"神社", ro:null, it:"santuario shintoista"},
    {jp:"びじゅつかん", kanji:"美術館", ro:null, it:"museo d'arte"},
    {jp:"しゃちょう", kanji:"社長", ro:null, it:"presidente d'azienda"},
    {jp:"かしゅ", kanji:"歌手", ro:null, it:"cantante"},
    {jp:"ルームメイト", kanji:null, ro:null, it:"coinquilino"},
    {jp:"ホストファミリー", kanji:null, ro:null, it:"famiglia ospitante"},
    {jp:"しょうらい", kanji:"将来", ro:null, it:"futuro"},
    {jp:"ゆめ", kanji:"夢", ro:null, it:"sogno"},
    {jp:"おまつり", kanji:"お祭り", ro:null, it:"festival"},
    {jp:"おしょうがつ", kanji:"お正月", ro:null, it:"Capodanno (giapponese)"},
    {jp:"おかし", kanji:"お菓子", ro:null, it:"dolcetti; snack"},
    {jp:"ビール", kanji:null, ro:null, it:"birra"},
    {jp:"おもちゃ", kanji:null, ro:null, it:"giocattolo"},
    {jp:"こんがっき", kanji:"今学期", ro:null, it:"questo semestre"},
    {jp:"らいがっき", kanji:"来学期", ro:null, it:"prossimo semestre"},
    {jp:"じゅぎょう", kanji:"授業", ro:null, it:"lezione (corso)"},
    {jp:"こちら", kanji:null, ro:null, it:"questa persona (forma cortese)"},
    {jp:"しゅっしん", kanji:"出身", ro:null, it:"provenire da (un luogo)"},
    {jp:"ひさしぶり", kanji:"久しぶり", ro:null, it:"è da tanto (che non ci si vede)"},
    {jp:"まあまあ", kanji:null, ro:null, it:"così così"},
    {jp:"もっと", kanji:null, ro:null, it:"di più"},
    {jp:"あと", kanji:"後", ro:null, it:"dopo (un evento)"},
    {jp:"そして", kanji:null, ro:null, it:"e poi"},
    {jp:"〜だけ", kanji:null, ro:null, it:"solo..."},
    {jp:"〜てん", kanji:"〜点", ro:null, it:"...punti"},
    {jp:"さっか", kanji:"作家", ro:null, it:"scrittore"},
    {jp:"ジャーナリスト", kanji:null, ro:null, it:"giornalista"},
    {jp:"けいさつかん", kanji:"警察官", ro:null, it:"poliziotto"},
    {jp:"しょうぼうし", kanji:"消防士", ro:null, it:"pompiere"},
    {jp:"きょうし", kanji:"教師", ro:null, it:"insegnante"},
    {jp:"けんきゅうしゃ", kanji:"研究者", ro:null, it:"ricercatore"},
    {jp:"うちゅうひこうし", kanji:"宇宙飛行士", ro:null, it:"astronauta"},
    {jp:"スポーツせんしゅ", kanji:"スポーツ選手", ro:null, it:"atleta"},
    {jp:"だいとうりょう", kanji:"大統領", ro:null, it:"presidente (di un paese)"},
    {jp:"はいゆう", kanji:"俳優", ro:null, it:"attore; attrice"},
    {jp:"かんごし", kanji:"看護師", ro:null, it:"infermiere/a"},
    {jp:"シェフ", kanji:null, ro:null, it:"chef"},
    {jp:"まんがか", kanji:"漫画家", ro:null, it:"fumettista"},
    {jp:"しめきり", kanji:null, ro:null, it:"scadenza"},
    {jp:"はつおん", kanji:"発音", ro:null, it:"pronuncia"},
    {jp:"ぶんぽう", kanji:"文法", ro:null, it:"grammatica"},
    {jp:"しつもん", kanji:"質問", ro:null, it:"domanda"},
    {jp:"こたえ", kanji:"答え", ro:null, it:"risposta"},
    {jp:"れい", kanji:"例", ro:null, it:"esempio"},
    {jp:"かっこ", kanji:null, ro:null, it:"parentesi"},
    {jp:"まる", kanji:null, ro:null, it:"segno di corretto (○)"},
    {jp:"ばつ", kanji:null, ro:null, it:"segno di sbagliato (×)"},
    {jp:"ほうげん", kanji:"方言", ro:null, it:"dialetto"},
    {jp:"きょうつうご", kanji:"共通語", ro:null, it:"lingua comune"},
    {jp:"たとえば", kanji:null, ro:null, it:"per esempio"},
    {jp:"ほかに", kanji:null, ro:null, it:"altro/qualcos'altro"}
  ],
  lezione12: [
    {jp:"おなか", kanji:null, ro:null, it:"stomaco; pancia"},
    {jp:"あし", kanji:"足", ro:null, it:"gamba; piede"},
    {jp:"のど", kanji:null, ro:null, it:"gola"},
    {jp:"は", kanji:"歯", ro:null, it:"dente"},
    {jp:"インフルエンザ", kanji:null, ro:null, it:"influenza"},
    {jp:"かぜ", kanji:"風邪", ro:null, it:"raffreddore"},
    {jp:"せき", kanji:null, ro:null, it:"tosse"},
    {jp:"ふつかよい", kanji:"二日酔い", ro:null, it:"postumi da sbornia"},
    {jp:"ホームシック", kanji:null, ro:null, it:"nostalgia di casa"},
    {jp:"アレルギー", kanji:null, ro:null, it:"allergia"},
    {jp:"ジュース", kanji:null, ro:null, it:"succo"},
    {jp:"たまご", kanji:"卵", ro:null, it:"uovo"},
    {jp:"ふく", kanji:"服", ro:null, it:"vestiti"},
    {jp:"もの", kanji:"物", ro:null, it:"cosa (oggetto concreto)"},
    {jp:"プレゼント", kanji:null, ro:null, it:"regalo"},
    {jp:"きっぷ", kanji:"切符", ro:null, it:"biglietto del treno"},
    {jp:"〜だい", kanji:"〜代", ro:null, it:"tariffa; costo"},
    {jp:"ようじ", kanji:"用事", ro:null, it:"commissione da sbrigare"},
    {jp:"おてあらい", kanji:"お手洗い", ro:null, it:"bagno"},
    {jp:"しあい", kanji:"試合", ro:null, it:"partita"},
    {jp:"せいじ", kanji:"政治", ro:null, it:"politica"},
    {jp:"せいせき", kanji:"成績", ro:null, it:"voto (a un test)"},
    {jp:"かのじょ", kanji:"彼女", ro:null, it:"lei; ragazza"},
    {jp:"かれ", kanji:"彼", ro:null, it:"lui; ragazzo"},
    {jp:"かれし", kanji:"彼氏", ro:null, it:"fidanzato"},
    {jp:"いみ", kanji:"意味", ro:null, it:"significato"},
    {jp:"にさんにち", kanji:"二三日", ro:null, it:"due o tre giorni"},
    {jp:"それに", kanji:null, ro:null, it:"inoltre"},
    {jp:"おなじ", kanji:"同じ", ro:null, it:"stesso"},
    {jp:"できるだけ", kanji:null, ro:null, it:"il più possibile"},
    {jp:"たぶん", kanji:"多分", ro:null, it:"probabilmente"},
    {jp:"もうすぐ", kanji:null, ro:null, it:"tra pochissimo"},
    {jp:"はじめて", kanji:"初めて", ro:null, it:"per la prima volta"},
    {jp:"おだいじに", kanji:"お大事に", ro:null, it:"guarisci presto"},
    {jp:"げんきがない", kanji:"元気がない", ro:null, it:"non stare bene, sembrare giù"},
    {jp:"ほけんしょう", kanji:"保険証", ro:null, it:"tessera assicurativa"},
    {jp:"いたみどめ", kanji:"痛み止め", ro:null, it:"antidolorifico"},
    {jp:"げり", kanji:"下痢", ro:null, it:"diarrea"},
    {jp:"べんぴ", kanji:"便秘", ro:null, it:"stitichezza"},
    {jp:"せいり", kanji:"生理", ro:null, it:"ciclo mestruale"},
    {jp:"かふんしょう", kanji:"花粉症", ro:null, it:"allergia al polline"},
    {jp:"むしば", kanji:"虫歯", ro:null, it:"carie"},
    {jp:"くしゃみ", kanji:null, ro:null, it:"starnuto"},
    {jp:"はなみず", kanji:"鼻水", ro:null, it:"naso che cola"},
    {jp:"はっしん", kanji:"発疹", ro:null, it:"eruzione cutanea"}
  ]
};

// Pool combinato di tutto il vocabolario dalla Lezione 1 alla Lezione 12.
// Ogni parola riceve un campo "lesson" per permettere di filtrare per capitolo nel quiz.
function withLesson(arr, n) { return arr.map(w => ({ ...w, lesson: n })); }
const VOCAB_ALL = [
  ...withLesson(VOCAB.lezione1, 1), ...withLesson(VOCAB.lezione2, 2), ...withLesson(VOCAB.lezione3, 3),
  ...withLesson(VOCAB.lezione4, 4), ...withLesson(VOCAB.lezione5, 5), ...withLesson(VOCAB.lezione6, 6),
  ...withLesson(VOCAB.lezione7, 7), ...withLesson(VOCAB.lezione8, 8), ...withLesson(VOCAB.lezione9, 9),
  ...withLesson(VOCAB.lezione10, 10), ...withLesson(VOCAB.utili4, 4),
  ...withLesson(VOCAB.lezione11, 11), ...withLesson(VOCAB.lezione12, 12)
];
